export const categorySupplementContent: Record<string, { paragraphs: string[] }> = {
  "deniz-kenari": {
    paragraphs: [
      "Türkiye'de deniz kenarı kamp rotası planlarken Ege ile Akdeniz'i aynı sezonda birleştirmek mümkündür: Haziran başında Çeşme-Alaçatı meltemi, Temmuz'da Datça'nın sakin koyları, Ağustos sonunda Kaş-Kalkan'ın daha ılıman geceleri farklı deneyimler sunar. Gökçeada gibi feribot gerektiren adalarda araç kontenjanı ve dönüş saati planlaması şarttır; Assos gibi antik kent yakınındaki koylarda ise park alanı sınırlılığı yaz akşamlarında belirginleşir.",
      "Deniz kenarı tesis seçiminde plaja mesafe, duş ve elektrik altyapısı, karavan bağlantısı ve gece güvenliği temel kriterlerdir. Caretta caretta yumurtlama alanlarında (özellikle Çıralı-Adrasan hattında) ışık kısıtlaması uygulanır; bu dönemde kırmızı ışık ve sessizlik kurallarına uyum zorunludur. Rehberimizdeki deniz kenarı listesi bu kriterlere göre süzülmüştür.",
      "Ege kıyısında meltem yönü kamp konforunu belirler: Alaçatı ve Ildırı açık kıyılarda rüzgâr güçlü eserken, Gökçeada'nın Yıldızkoy ve Datça'nın Hayıtbükü gibi korunaklı koylarda gece uykusu daha rahattır. Kum zeminde derin kazık, rüzgâr ipi ve kum torbası ağırlık sistemi meltem gecelerinde çadır stabilitesini korur. Deniz suyuyla temas sonrası tatlı su stoku kritiktir; birçok koyda musluk suyu veya tesis duşu dışında kaynak bulunmaz. Gün batımından sonra kıyı sıcaklığı hızla düşer; deniz kenarı kampında termal içlik ve rüzgâr kesici katman gece konforunu belirgin artırır.",
      "Akdeniz kıyısında koy seçimi mevsime göre değişir: haziran-temmuz'da Kaş-Üçağız batık şehir manzaralı koylar, ağustos sonunda Fethiye Kabak yamaçları kalabalıktan arınır. Deniz kenarı kampında gelgit etkisi sınırlı olsa da kıyı çizgisine çok yakın kurulan çadırlar gece dalga sesiyle birlikte su birikintisi riski taşır; yüksek tabanlı mat ve eğimli zemin tercih edilmelidir. Plastik atık ve cam şişe kıyı ekosistemine doğrudan zarar verir; deniz kaplumbağası ve monk seal gözlemlerinde minimum mesafe korunmalıdır.",
    ],
  },
  dag: {
    paragraphs: [
      "Türkiye'de dağ kampı coğrafyası birbirinden farklı zorluk seviyeleri sunar: Kaçkar'da çok günlü trekking ve yüksek rakım, Kazdağı'nda orman içi orta zorluk, Kartepe'de araçla erişilebilir yamaçlar. Yusufeli ve Rize vadilerinde nehir kenarı kamp noktaları rafting sezonuyla örtüşür; Haziran-Eylül arası su seviyesi ve hava koşulları günlük takip gerektirir.",
      "Dağ kampında acil durum planı oluşturmak kritiktir: En yakın sağlık merkezi, telefon çekim noktaları ve alternatif iniş rotası önceden belirlenmelidir. Yayla döneminde (Temmuz-Ağustos) yerel transhumans kültürüne saygı göstermek, hayvan sürülerinin geçiş alanlarına müdahale etmemek önemlidir.",
      "Kaçkar ve Aladağlar gibi çok günlü rotalarda günlük rakım kazancı 800-1200 metre olabilir; yüksek irtifa hastalığı belirtileri (baş ağrısı, mide bulantısı) görüldüğünde iniş planlanmalıdır. Dağ kampında su kaynağı haritalama zorunludur: Yusufeli-Barhal patikalarında yağmur sonrası dere debisi artarken, Kazdağı yaz sonunda kaynakları kurutabilir. Gece sıcaklığı rakıma göre her 300 metrede 2 derece düşer; 2000 metre üzeri yaz gecelerinde bile sıfırın altına inebilir. Dağ ekipmanında trekking batonları, su geçirmez bot ve katmanlı giyim sistemi temel üçlüdür.",
      "Orta zorluk dağ kampı (Kartepe, Spil Dağı, Kazdağı etekleri) araçla erişilebilir alanlarda günübirlik veya tek gece programına uygunken, zor rotalar (Kaçkar zirve, Erciyes buzul sınırı) çok günlük plan ve deneyim gerektirir. Dağ kampında hava değişimi hızlıdır; sabah güneşli başlayan bir gün öğleden sonra sis ve yağmura dönebilir. Karadeniz dağlarında yıllık yağış 2500 mm'yi aştığından çadır su geçirmezlik derecesi minimum 3000 mm olmalı; İç Anadolu dağlarında ise gece radyasyon soğuması daha belirgindir.",
    ],
  },
  orman: {
    paragraphs: [
      "Orman kamp alanları Türkiye'de milli park sınırları (Yedigöller, Kazdağı, Olympos) ile özel işletme orman tesisleri olarak ikiye ayrılır. Milli parklarda giriş saati, ücret ve çadır kurulum bölgesi net kurallarla belirlenir; özel tesislerde ise elektrik, duş ve market erişimi daha esnek olabilir. Yangın yasağı dönemlerinde (genellikle yaz ayları) açık ateş tamamen yasaklanabilir.",
      "Orman içi nem oranı kıyıya göre yüksektir; gece yoğuşması çadır içinde birikir. Havalandırmalı çadır, su geçirmez zemin örtüsü ve hafif polar katman gece konforunu artırır. Kartepe ve Mudurnu gibi Marmara'ya yakın orman noktaları hafta sonu yoğunluğu yaşarken, Olympos vadisi sezon boyunca sürekli talep görür.",
      "Yedigöller ve Kazdağı gibi milli parklarda çadır kurulum bölgesi park yönetimi tarafından belirlenir; giriş kapısından itibaren araç trafiği kısıtlı alanlarda ekipman sırt çantasıyla taşınmalıdır. Orman zemininde kök sistemi çadır tabanını delik deşik eder; kalın zemin örtüsü ve hava yastıklı mat konforu korur. İlkbaharda orman zemininde biriken nem ve sonbaharda düşen yaprak tabakası kayganlık riski yaratır; kamp alanı seçiminde eğim ve drenaj dikkate alınmalıdır. Orman yangını riski yüksek dönemlerde (temmuz-ağustos) açık ateş tamamen yasaktır; taşınabilir gaz ocak ve sıvı yakıt tüpleri zorunlu alternatiftir.",
      "Abant ve Belgrad Ormanı gibi çam ağırlıklı ormanlarda reçine damlaması çadır kumaşına zarar verir; Macahel gürgen ormanlarında ise nem oranı daha yüksektir. Orman kampında vahşi yaşam karşılaşmaları (domuz, ayı, kurt) nadirdir ancak gıda saklama kurallarına uyulmalı; açıkta bırakılan yiyecekler hayvanları çeker. Sonbahar orman kampı (Yedigöller, Bolu) Türkiye'nin en fotojenik mevsim deneyimini sunar; gece sıcaklığı sıfırın altına düşebileceğinden üç mevsim uyku tulumu taşınmalıdır.",
    ],
  },
  kislik: {
    paragraphs: [
      "Kış kampı için Türkiye'de üç ana coğrafya öne çıkar: Marmara'da Kartepe kar yağışı, Bolu'da Abant gölü buz manzarası, Doğu Karadeniz'de Kaçkar eteklerinde erken kış karları. Her bölgede gece sıcaklığı farklı düşer; Kartepe'de -5°C, Yusufeli yaylalarında -10°C altı mümkündür. Dört mevsim çadır veya karavan ısıtması bu koşullarda hayati önem taşır.",
      "Kışlık tesis seçiminde sıcak su, elektrik kesintisine karşı yedek plan ve karlı yola erişim bilgisi sorulmalıdır. Gün ışığı kısa olduğundan kamp kurulumu en geç 16:00'ya kadar tamamlanmalı; kafa feneri, termos ve ekstra battaniye standart ekipmandır.",
      "Kartepe kış kampında kar tabakası 30-60 cm kalınlığa ulaşabilir; kar kazığı ve geniş tabanlı kazık sistemi çadır stabilitesini sağlar. Abant Gölü kıyısında ocak-şubat döneminde göl yüzeyi kısmen donar; bu manzara fotoğraf kampı için eşsizdir ancak gece -15°C'ye kadar düşen sıcaklık dört mevsim uyku tulumu (-10°C comfort rating) gerektirir. Kartalkaya kayak merkezi yaz aylarında telesiyejle 2200 metre rakıma çıkar; kışın aynı alan kar kampı ve snowboard için kullanılır. Kış kampında nem yönetimi kritiktir: nefes alan çadır kumaşı ve uyku tulumu içinde biriken yoğuşma soğuk hissi yaratır.",
      "Doğu Anadolu kış kampı (Palandöken, Tortum) -30°C'ye kadar inen sıcaklıklarla Türkiye'nin en zorlu koşullarını sunar; bu bölgelerde karavan ısıtması ve yedek yakıt stoku hayati önem taşır. Karadeniz kış kampında (Ayder, Zigana) yağış kar yerine sulu kar ve dondurucu rüzgâr formunda gelir; su geçirmez dış katman ve rüzgâr kesici daha kritiktir. Kış kampında gün ışığı 9-10 saatle sınırlıdır; aktivite planlaması 07:00-16:00 aralığına sıkıştırılmalıdır.",
    ],
  },
  festival: {
    paragraphs: [
      "Festival kamp alanları Türkiye'de yaz aylarında Ege kıyısı (Alaçatı, Çeşme) ve Akdeniz (Fethiye, Olympos) etrafında yoğunlaşır. Festival döneminde normal kamp alanları kapasite ve gürültü profilini değiştirebilir; rezervasyon onayı ve etkinlik takvimi birlikte planlanmalıdır. Grup halinde kamp kurmak güvenlik ve ekipman paylaşımı açısından avantaj sağlar.",
      "Festival kampında portatif şarj, su matarası, kulak tıkacı ve su geçirmez çadır zorunlu sayılır. Değerli eşyaları çadırda bırakmamak, gece dönüş rotasını gün ışığında keşfetmek pratik güvenlik önlemleridir. Etkinlik sonrası alanı temiz bırakmak gelecek sezon erişimini korur.",
      "Alaçatı ve Çeşme'deki yaz festivalleri döneminde normal kamp alanları kapasite, gürültü profili ve fiyatlandırmada değişir; rezervasyon onayı etkinlik takvimiyle birlikte planlanmalıdır. Olympos ve Kabak'taki alternatif müzik ve doğa festivalleri vadilerde yoğunlaşır; bu dönemde su kaynağı tüketimi artar ve çöp hacmi yükselir. Festival kamp alanında komşu çadırlarla güvenlik ağı oluşturmak (birbirinin ekipmanına göz kulak olmak) pratik bir önlemdir. Kulak tıkacı ve göz bandı, gece saat 02:00'ye kadar sürebilen sahne performanslarında uyku kalitesini korur.",
      "Fethiye ve Datça'daki deniz ve doğa festivalleri tekne ulaşımı gerektiren koylarda düzenlenir; feribot veya zodiac transfer saatleri kamp programına dahil edilmelidir. Festival sonrası alan temizliği (camping leave no trace) gelecek yıl aynı alana erişimi belirler; birçok işletme festival döneminde ek kurallar uygular. Grup halinde festival kampı ekipman paylaşımı (ortak ocak, su filtresi, ilk yardım kiti) hem maliyeti düşürür hem güvenliği artırır.",
      "Türkiye'de festival kampı planlarken etkinlik biletini, kamp alanı rezervasyonunu ve ulaşımı aynı pakette değerlendirmek sürpriz maliyetleri önler; bazı festivaller kamp alanını bilet fiyatına dahil ederken bazıları ayrı satar.",
      "Ege ve Akdeniz festival kampında gece nem oranı yüksektir; nefes alan çadır kumaşı ve hafif uyku tulumu sabah konforunu belirgin artırır.",
    ],
  },
  karavan: {
    paragraphs: [
      "Türkiye karavan rotası genellikle İstanbul veya Ankara çıkışlı Marmara (Kartepe, Sapanca), Ege (Çeşme, Urla, Assos) ve Akdeniz (Kaş, Fethiye) halkalarından oluşur. Tam donanımlı karavan parklarında 220V elektrik, temiz su ve gri su boşaltma standart beklentidir; kıyı koylarında ise sınırlı altyapılı doğal parklar tercih edilir.",
      "Karavan boyutu dar köy yollarında (Datça, Kaş yarımadaları, Gökçeada) erişimi kısıtlayabilir; 7 metrenin üzeri araçlar için rota önceden harita üzerinde doğrulanmalıdır. Uzun konaklamalarda tesisle haftalık indirim görüşmesi yapılabilir; yaz sezonunda elektrik kontenjanı sınırlı olabilir.",
      "Türkiye karavan rotasında elektrik kontenjanı yaz sezonunda (temmuz-ağustos) tesislerde sınırlıdır; solar panel veya jeneratör yedek planı uzun konaklamalarda zorunludur. Gri su ve siyah su boşaltma noktaları her tesisde bulunmaz; Sapanca-Kartepe hattındaki tam donanımlı parklar ile Datça koylarındaki sınırlı altyapılı alanlar arasında planlama farkı büyüktür. Karavan boyutu 7 metreyi aştığında Gökçeada feribot araç kontenjanı, Datça dar virajları ve Kaş yarımadası park alanı sorunları ortaya çıkar. Kış karavan kampında (Abant, Kartepe) boru donması riski vardır; tank ısıtıcı ve antifriz kullanımı kontrol edilmelidir.",
      "İstanbul-Ankara çıkışlı karavan rotası genellikle Marmara halkası (Sapanca, Kartepe, Abant) ile başlar; Ege halkası (Assos, Urla, Çeşme) ve Akdeniz halkası (Kaş, Olympos, Fethiye) ikinci aşamada birleştirilir. Karavan parklarında komşu mesafe ve gürültü kuralları tesis bazında değişir; gece jeneratör kullanımı birçok alanda yasaktır. Uzun konaklamalarda (7+ gece) tesisle haftalık indirim görüşmesi yapılabilir; sezon ortasında elektrik ve su fiyatlandırması ayrı hesaplanır.",
      "Karavan turizminde rota planlama uygulamaları (Park4Night, karavan parkı listeleri) Türkiye'deki tesis yoğunluğunu önceden gösterir; özellikle Gökçeada ve Datça gibi ada-yarımada rotalarında rezervasyon zorunluluğu yaz sezonunda erken planlamayı gerektirir.",
      "Karavan parklarında gece jeneratör yasağı olan tesislerde sessiz saatler (genellikle 23:00-07:00) komşu konforu için kesinlikle uygulanmalıdır.",
    ],
  },
  bungalov: {
    paragraphs: [
      "Bungalov kamp konsepti Türkiye'de özellikle Urla bağ evleri, Datça koyları, Kalkan yamaçları ve Olympos vadisinde yaygındır. Çadır kurmadan doğada kalmak isteyen aileler için ideal geçiş basamağıdır; yatak, banyo ve elektrik imkânı sunarken gece doğa seslerini deneyimlemeye devam edersiniz. Deniz manzaralı teraslı birimler gün batımı için, orman içi birimler yaz sıcağında serinlik için tercih edilir.",
      "Bungalov rezervasyonunda iptal politikası, evcil hayvan kuralı, kahvaltı dahil olup olmadığı ve plaja/merkeze mesafe netleştirilmelidir. Yoğun sezonda (Temmuz-Ağustos) haftalar öncesinden rezervasyon şarttır; ilkbahar ve sonbahar daha uygun fiyat ve sakin ortam sunar.",
      "Olympos vadisindeki ağaç ev ve taş bungalovlar çadır kampına geçiş basamağı olarak aileler arasında popülerdir; elektrik ve banyo imkânı sunarken gece çam ormanı sesleri korunur. Kalkan yamaçlarındaki teraslı bungalovlar gün batımı manzarası için, Urla bağ evlerindeki birimler ise şarap rotası entegrasyonu için tercih edilir. Datça koylarındaki ahşap bungalovlarda su ve market erişimi sınırlı olabilir; tesis öncesi stok planlaması sorulmalıdır. Bungalov seçiminde zemin tipi (taş, ahşap, toprak) gece sıcaklığını etkiler; deniz manzaralı birimler rüzgârlı, orman içi birimler nemli gece sunar.",
      "Kabak Koyu ve Olympos'ta bungalov fiyatları sezon ortasında (ağustos) zirve yapar; mayıs-haziran ve eylül-ekim arası %30-40 daha uygun fiyat ve sakin ortam sunar. Bungalov rezervasyonunda iptal politikası, evcil hayvan kuralı ve kahvaltı dahil olup olmadığı netleştirilmelidir. Çadır kampına kıyasla bungalov daha az esneklik sunar (check-in/check-out saatleri, alan sınırları) ancak yağmurlu gecelerde ve aile kampında konfor avantajı belirgindir.",
      "Bungalov tesislerinde mutfak ve buzdolabı imkânı çadır kampına göre yemek planlamasını kolaylaştırır; ancak tesis dışına çıkmadan yemek hazırlama kuralı olan işletmelerde bu avantaj sınırlı kalabilir.",
      "Datça ve Kalkan bungalovlarında gece rüzgârı deniz manzaralı teraslarda serinlik getirir; yanında hafif polar veya rüzgâr kesici bulundurmak akşam oturumlarını rahatlatır.",
    ],
  },
};
