export const districtSupplementContent: Record<string, { paragraphs: string[] }> = {
  "izmit/kartepe": {
    paragraphs: [
      "Kartepe kamp rotası çoğu zaman Sapanca ve Maşukiye ile birleştirilir; sabah Maşukiye'de kahvaltı, öğleden sonra Kartepe yamaçlarında çadır kurmak hafta sonu programının klasik akışıdır. Teleferik hattının üst istasyonu kışın kayak, yazın yürüyüş başlangıcı olarak kullanılır; kamp alanı seçerken istasyona mesafe hem ulaşım hem manzara açısından belirleyicidir. İstanbul'dan otoyol üzerinden yaklaşık bir buçuk saatlik mesafe, gece yarısı çıkışlı kamp planlarını bile mümkün kılar. Kış aylarında kar yağışı zirvelerde kalın tabaka oluşturur; kar kampı deneyimi arayanlar ocak-şubat dönemini tercih eder. İlkbahar ve sonbahar orman yürüyüşleri, yaz sıcağından kaçınmak isteyenlere ideal alternatif sunar.",
      "Bölgede dere kenarı nem oranı yüksektir; gece sıcaklığı gündüze göre belirgin düşer ve çadır altı izolasyon önem kazanır. Hafta sonu Sapanca çevresinde park yeri aramak zaman alabileceğinden, Cumartesi sabahı erken varış veya Cuma akşamı kamp kurulumu konforu artırır. Orman içi alanlarda açık ateş yasakları sıkı uygulanır; taşınabilir ocak ve yeterli su stoku temel ihtiyaçlar arasındadır. Maşukiye'deki restoran yoğunluğu kamp alanı seçiminde gürültü faktörü olarak değerlendirilmelidir. Dere kenarındaki gölgeli alanlar yaz sıcağında serinlik sunarken su seviyesi değişimlerini düzenli izlemek güvenlik açısından önem taşır.",
      "TEM otoyolu Kartepe çıkışı ilçenin ana ulaşım kapısıdır; İstanbul'dan 90 dakika, Ankara yönünden D-100 ile aynı mesafe. Ocak-şubat kar kampı, nisan-mayıs orman yürüyüşü, haziran-ağustos serin geceler, eylül-ekim yaprak dökümü mevsim matrisini oluşturur.",
    ],
  },
  "canakkale/assos": {
    paragraphs: [
      "Assos'ta kamp deneyiminin merkezinde Behramkale'nin taş evleri ve antik liman manzarası yer alır. Kadırga Koyu ile Assos Limanı arasındaki kıyı şeridi, rüzgâr yönüne göre farklı karakter sunar: liman tarafı akşam sakinleşirken açık koylarda meltem gece boyunca esmeye devam edebilir. Antik kent girişine yakın noktalarda kamp kuralları sit alanı düzenlemelerine tabidir; çadır rengi ve alan sınırları işletme veya belediye yönergelerine göre değişir. Athena Tapınağı'ndan izlenen gün batımı, Assos kampının en karakteristik anlarından birini oluşturur. Behramkale'nin dar taş sokakları araç parkını zorlaştırır; kamp ekipmanı taşımayı hafif sırt çantasıyla planlamak pratiklik sağlar.",
      "Assos'a Çanakkale veya Edremit üzerinden gelenler, Behramkale'nin dar sokaklarında araç parkını önceden planlamalıdır. Su kaynağı çoğu özel alanda sağlanır; doğal kaynaklara güvenmek risklidir. Mayıs sonu ve haziran başı, deniz suyu henüz soğuk olsa da kalabalık öncesi en dengeli dönemdir; eylülde antik tiyatro çevresinde gün batımı seyri kamp programına kolayca eklenebilir. Öğleden sonra kuvvetlenen rüzgârda çadır kurulumu sabah erken saatlere alınmalıdır. Çöpün geri götürülmesi ve sit alanı kurallarına uyulması, Assos'un sürdürülebilir kamp geleneğinin temelini oluşturur.",
      "Edremit-Ayvalık yolu Assos'a en kısa kıyı bağlantısını sunar; Behramkale otoparkından Kadırga Koyu'na yürüyüş 20 dakika. Mayıs-haziran meltem öncesi dönem, eylül antik tiyatro gün batımı ideal kamp pencereleridir.",
    ],
  },
  "canakkale/gokceada": {
    paragraphs: [
      "Gökçeada kamp planı feribot saatlerine kilitlenir: Kabatepe iskelesinden adaya geçiş en az bir buçuk saat sürer ve dönüş rezervasyonu yapılmadan birkaç günlük program risk taşır. Aydıncık'ın rüzgârlı kumsalı sörf ve açık deniz kampına uygunken, Yıldızkoy ve Laz Koyu daha korunaklıdır. Adanın iç kesimlerindeki Yeni Bademli, Tepeköy ve Kaleköy gibi yerleşimler, kıyıdan farklı bir köy kamp atmosferi sunar. Türkiye'nin ilk Cittaslow adası unvanı, burada yavaş tempolu ve doğaya saygılı kamp anlayışını destekler. Gökçeada'da en az üç günlük program, adanın farklı koy karakterlerini deneyimlemek için makul bir süredir.",
      "Adada market ve benzin istasyonu dağılımı seyrektir; Kuzulimanı ve Merkez dışındaki koylarda en az iki günlük su ve yakıt stoku önerilir. Yaz meltemi çadır kazıklarını zorlar; kum zeminde derin kazık ve ekstra ip seti şarttır. İlkbaharda ada çiçekleri ve boş plajlar, yaz ortasına kıyasla çok daha sakin bir kamp ortamı yaratır. Badem ve zeytin hasat dönemlerinde köy pazarları taze ürün stoklamak için ideal fırsat sunar. Rüzgâr yönüne göre koy seçimi, gece boyunca konforlu uyku için belirleyici faktördür.",
      "Kabatepe feribot iskelesi ada kampının tek hub'ıdır; araç rezervasyonu yaz sezonunda haftalar öncesinden dolar. Nisan-mayıs badem çiçeği, haziran-ağustos meltem, eylül-ekim tenha koylar mevsim matrisini belirler.",
    ],
  },
  "izmir/cesme": {
    paragraphs: [
      "Çeşme Yarımadası'nda kamp alanı seçimi meltem yönüne göre yapılmalıdır: Alaçatı ve Ilıca açık kıyılarda rüzgâr güçlü eserken, Ildırı ve Paşalimanı gibi koylar daha korunaklıdır. Sakız Adası'nın silueti gün batımında Ildırı antik kentinden net görülür; burada geceleyenler hem tarih hem deniz manzaralı bir durak elde eder. Yarımadanın termal kıyıları Ilıca ve Şifne çevresinde kamp tesisleri yoğunlaşır. Alaçatı'nın taş evleri ve rüzgâr sörfü okulları, kamp gününe su sporları eklemek isteyenlere geniş seçenek sunar. Yarımadanın batı koyları melteme karşı daha korunaklıdır; çadır kurulumu bu yönde planlanmalıdır.",
      "Temmuz-ağustos döneminde hafta sonları otoyol girişleri tıkanabilir; Perşembe akşamı varış veya hafta içi kamp hafta sonu kalabalığından kaçınmanın en pratik yoludur. Çeşme'de tatlı su kaynakları sınırlıdır; çoğu tesis musluk suyu veya depo ile hizmet verir. Rüzgâr sörfü ekipmanı taşıyanlar Alaçatı koylarına yakın kamp alanlarını tercih ederek günlük aktivite mesafesini kısaltabilir. Haziran başı ve eylül ortası, hem deniz suyu sıcaklığı hem de kamp alanı müsaitliği açısından altın sezon kabul edilir. Bazı koylarda özel mülkiyet sınırları geçerlidir; kamp öncesi alan araştırması yapılmalıdır.",
      "Otoyol Çeşme çıkışı ve havalimanı bağlantısı ilçenin ulaşım omurgasıdır. Haziran başı-eylül ortası altın sezon; Ildırı antik kentinden Sakız silueti gün batımında net görülür.",
    ],
  },
  "izmir/urla": {
    paragraphs: [
      "Urla'nın kamp coğrafyası Karaburun yarımadasına doğru incelir: merkez bağları ve şarap rotaları ile kıyı koyları farklı tempoda gezilir. Barbaros ve Özbek koyları deniz kampı için en çok tercih edilen noktalardır; Özbek'te taş zemin ve rüzgârlı hava çadır seçimini etkiler. Urla Bağ Yolu üzerindeki üreticiler, kamp rotasına tadım molası ekler; ancak bağ arazilerinde izinsiz çadır kurulmaz. Cittaslow ruhu, Urla'da kamp temposunu yavaşlatır ve yerel üreticilerle doğrudan temas imkânı sunar. Karaburun yarımadasının uç noktalarına uzanan koylar, kalabalıktan uzak kamp arayanlara hitap eder.",
      "İzmir'den Urla'ya hafta sonu trafiği sabah erken saatlerde yoğunlaşır; kamp kurulumu için Cuma akşamı varış avantaj sağlar. Urla'da organize kamp alanlarının bir kısmı karavan parkı olarak da hizmet verir; elektrik bağlantısı olan tesisler yaz aylarında hızla dolabilir. Sonbahar hasat döneminde bağ yaprakları sararır ve kıyı kampına farklı bir renk paleti eklenir. Sanat galerileri ve deniz ürünleri restoranları, Urla kamp rotasını gastronomi ve kültür duraklarıyla zenginleştirir. Meltem rüzgârı yaz aylarında çadır seçiminde dikkat gerektirir; sağlam kazık ve ekstra ip seti önerilir.",
      "Karaburun yarımadası yolu Özbek ve Barbaros koylarına dağılır; İzmir merkeze 45 dakika. Eylül bağ hasadı ve sonbahar meltemi sonrası sakin dönem en verimli kamp penceresidir.",
    ],
  },
  "izmir/seferihisar": {
    paragraphs: [
      "Seferihisar'da Sığacık Kalesi'nin iç limanı kamp gününe yürüyüş rotası olarak eklenebilir; kale surlarından Ege manzarası, akşam saatlerinde balıkçı teknesi hareketliliği ile birleşir. Teos antik kentinin zeytinlikler arasındaki kalıntıları, kıyı kampından iç kesime geçiş yapanlar için yarım günlük keşif imkânı sunar. Akkum ve Ürkmez plajları aile kampına uygun geniş kıyı şeridi sağlar. Türkiye'nin ilk Cittaslow ilçesi olarak Seferihisar, sürdürülebilir kamp anlayışını resmi statüyle destekler. Sığacık limanındaki balıkçı faaliyetlerine alan bırakmak, yerel yaşam ritmine saygının bir parçasıdır. İlkbahar ve sonbahar, Ege'nin ılıman ikliminde ideal kamp dönemleridir.",
      "Cittaslow ilçe statüsü burada gürültü ve ışık kirliliğine karşı daha düşük tolerans anlamına gelir; gece geç saatlerde yüksek ses kamp alanı komşularını rahatsız edebilir. Mandalina bahçeleri ilkbaharda çiçek açar; bu dönemde kırsal yollar traktör trafiği taşır. Sığacık'ta pazar günleri köy pazarı kurulur; taze sebze ve deniz ürünü stoklamak kamp mutfağını zenginleştirir. Mandalina hasat dönemi yaz ortasında farklı bir kırsal atmosfer yaratır. Mandalina bahçelerine ve özel arazilere izinsiz girilmemesi, Cittaslow ilkelerinin temel gereksinimlerindendir.",
      "Sığacık otogar bağlantısı araçsız kampçılara ulaşım sunar. Nisan-mayıs mandalina çiçeği, haziran-ağustos kalabalık, eylül-ekim Teos antik kent molası ideal dönemdir.",
    ],
  },
  "izmir/dikili": {
    paragraphs: [
      "Dikili kamp rotasının omurgasını Nebiler Şelalesi ve Kazdağı etekleri oluşturur. Şelaleye giden patika yaz aylarında kayganlaşır; kamp ekipmanı taşırken hafif sırt çantası tercih edilmelidir. Bademli Koyu, Dikili merkeze yakın sakin bir deniz kampı alternatifi sunarken Çandarlı'nın antik liman kalıntıları ve kale manzarası tarih meraklılarına ayrı bir durak oluşturur. Denizköy plajı ise geniş kum alanıyla aile kampına uygundur. Kazdağı'nın batı eteklerinde orman yürüyüşleri, aynı gün içinde kıyı kampıyla birleştirilebilir. Nebiler Şelalesi çevresindeki ormanlık alan, yaz sıcağında serin bir kamp ortamı sunar.",
      "Kazdağı yamaçlarında yaz yangın yasağı dönemlerinde açık ateş kesinlikle kurulmamalıdır; ilgili milli park duyuruları her sezon güncellenir. Dikili'nin kuzey koylarına ulaşım virajlı köy yollarından geçer; büyük karavanlar bazı noktalarda manevra zorluğu yaşayabilir. İlkbahar ve sonbahar, hem şelale debisinin yüksek olduğu hem de kıyı kalabalığının azaldığı ideal kamp dönemidir. Nebiler Şelalesi çevresindeki nemli orman zemininde gece sıcaklığı kıyıya göre birkaç derece düşer. Kazdağı eteklerinde denize karşı kurulan çadır, Dikili'nin en otantik kamp imgesini oluşturur.",
      "Nebiler Şelalesi patikası sabah erken başlanmalı; Çandarlı Kalesi gün batımı molası, Kazdağı Hasanboğuldu girişine 40 dakika mesafededir. Nisan-ekim arası patika-kıyı kombinasyonu en verimli dönemdir. Bergama antik kentinden Dikili'ye uzanan kıyı şeridi, tarih ve kamp rotasını birleştiren iki günlük programlar için uygundur.",
    ],
  },
  "mugla/fethiye": {
    paragraphs: [
      "Fethiye'de çok günlü kamp programları genellikle Kabak Koyu veya Ölüdeniz'den başlayıp Likya Yolu üzerinde devam eder. Kabak'taki yamaç kamp alanları gece manzarasıyla ünlüdür ancak yokuş aşağı inmek ekipman taşımayı zorlaştırır; hafif çadır ve sırt çantası tercih edilir. Kelebekler Vadisi sezonluk ziyaret kısıtlamalarına tabidir; kamp öncesi güncel giriş kuralları kontrol edilmelidir. Likya Yolu'nun Fethiye çıkışlı etapları, antik kaya mezarları ve turkuaz koy manzaraları eşliğinde trekking ve kampı birleştirir. Yamaç yollardaki araç güvenliği, Kabak gibi popüler noktalarda erken varış planlamasıyla birlikte değerlendirilmelidir.",
      "Kayaköy'ün terk edilmiş taş evleri günübirlik ziyaretçi akınına açıktır; gece burada kamp kurulmaz ancak yakın tesislerden yürüyüş rotasına dahil edilebilir. Ölüdeniz lagünü çevresinde rüzgâr sörfü ve yamaç paraşütü aktiviteleri yoğundur; kamp alanı seçerken havaalanına yakınlık gürültü faktörü olabilir. Eylül sonu deniz suyu hâlâ ılıkken Likya patikalarındaki kalabalık belirgin biçimde azalır. Mayıs-haziran dönemi, yaz sıcağından kaçınmak isteyen kampçılar için en verimli aylardır. Deniz ile orman arasındaki sıcaklık farkına göre katmanlı giyinmek, Fethiye kampının temel ekipman gereksinimidir.",
      "Dalaman Havalimanı 45 dakika mesafededir; Kabak Koyu yolu dar virajlıdır. Mayıs-haziran Likya etapları, eylül deniz sıcaklığı ideal kamp pencerelerini oluşturur.",
    ],
  },
  "mugla/datca": {
    paragraphs: [
      "Datça Yarımadası'nda Knidos antik kentinin batı ucundaki fener noktası, kamp gününe tarihî keşif eklemek isteyenler için yarım günlük rota oluşturur. Palamutbükü ve Domuzbükü arasındaki koylar farklı rüzgâr koşulları sunar: meltem güneybatıdan estiğinde Palamutbükü daha korunaklı kalabilir. Hayıtbükü'nün dar girişi dalgaları kırar; bu nedenle açık deniz kampına kıyasla daha sakin bir gece uyku imkânı verir. Ege ile Akdeniz'in buluştuğu yarımada ucu, Datça kamp deneyimine coğrafi bir ayrıcalık katar. Knidos'ta gün batımı manzarası, antik tiyatro kalıntıları eşliğinde kamp programına tarihî derinlik ekler.",
      "Yarımadada bazı koylarda elektrik ve su altyapısı yoktur; güneş paneli veya powerbank uzun kamp programları için gereklidir. Datça merkez dışındaki marketlere erişim mesafeli olabilir; Palamutbükü'ne gitmeden önce su ve gıda stoku yapılmalıdır. İlkbaharda badem çiçekleri yarımadanın iç yollarını beyaza boyar; bu dönem kamp fotoğrafçılığı için en verimli mevsimdir. Dar ve virajlı yarımada yolunda karşılaşma manevralarına hazırlıklı olmak, özellikle gece sürüşünde güvenlik açısından kritiktir. Yarımadanın su ve market imkânlarının sınırlı olduğu koylarda stok planlaması, en az birkaç günlük program için zorunludur.",
      "Marmaris-Datça yolu yarımadanın ana arteridir; Knidos fener noktası batı ucunda. Şubat-mart badem çiçeği, haziran-ağustos meltem, eylül tenha koylar mevsim matrisini belirler.",
    ],
  },
  "mugla/marmaris": {
    paragraphs: [
      "Marmaris kamp rotasında Gökova Körfezi kıyıları merkez kalabalığından ayrışır: Akyaka'nın Azmak Nehri delta manzarası, kitesurf ve sakin kampı bir arada arayanlara hitap eder. Selimiye ve Bozburun yarımadasındaki koylar daha az ticarileşmiştir; ulaşım süresi uzasa da gece sessizliği ödüllendiricidir. İçmeler ve Turunç, Marmaris merkeze yakın alternatifler sunar ancak yaz yoğunluğu yüksektir. Bayır köyünün yel değirmenleri, Gökova rotasına kısa bir kültür molası ekler. Gökova kıyısındaki sakin koylar, kalabalık Marmaris merkezine alternatif sunarak kamp deneyimini farklılaştırır.",
      "Gökova yolunda dar virajlar ve yaya geçişleri dikkat gerektirir; gece sürüşünde yaban domuzu ve keçi sürüsüne rastlanabilir. Körfez kıyısındaki çam ormanlarında yangın riski yaz aylarında artar; sigara izmariti ve cam atığı ciddi tehdit oluşturur. Mayıs ve eylül ayları hem deniz suyu sıcaklığı hem de kamp alanı müsaitliği açısından altın dönem kabul edilir. Karavan parkları körfez boyunca yaygındır; elektrik bağlantılı tesisler yaz sezonunda erken rezervasyon gerektirir. Yaz trafiğinde erken hareket etmenin avantaj sağlayacağı unutulmamalıdır. Orman yangını riskine karşı dikkatli olmak, Marmaris kampının temel güvenlik gereksinimlerindendir.",
      "Gökova Azmak Nehri delta yolu Akyaka'ya, Bozburun yarımadası yolu Selimiye koylarına dağılır. Mayıs-eylül altın dönem; yaz ortasında orman yangını yasağına dikkat edilmelidir.",
    ],
  },
  "balikesir/edremit": {
    paragraphs: [
      "Edremit Körfezi kamp rotası Kazdağı patikaları ile kıyı şeridini birleştirir. Altınoluk, zeytin gölgeli sahil şeridi ve organize tesisleriyle en çok tercih edilen duraktır; Akçay ve Ören ise daha geniş kumsal alanı sunar. Kazdağı Milli Parkı girişinden Hasanboğuldu ve Sütuven Şelalesi'ne giden yürüyüşler, sabah erken başlayıp akşam kıyı kampına dönülecek şekilde planlanabilir. Antandros antik kenti Altınoluk yakınında deniz seviyesinde kalıntılar barındırır; kamp gününe kısa bir tarih molası eklenir. Zeytinlikler arasında kurulan çadır, Edremit kampının en ayırt edici görsel imgesini oluşturur. Kazdağı patikalarındaki serin orman havası, yaz ortasında kıyı kampına hoş bir alternatif sunar.",
      "Körfez boyunca zeytin hasat dönemi kasım-aralık aylarına denk gelir; bu mevsimde kırsal yollarda traktör trafiği artar ancak kıyı kalabalığı azalır. Kazdağı yamaçlarında gece sıcaklığı kıyıya göre birkaç derece düşer; yayla ve orman kampı için ek katman gerekir. Edremit havalimanı yakınlığı, uçakla gelen kampçılar için lojistik avantaj sağlar. Kazdağı patikalarında yaz yangın yasağı dönemlerinde açık ateş kesinlikle kurulmamalı; taşınabilir ocak ve yeterli su stoku zorunludur. Kıyıda meltem rüzgârına karşı sağlam çadır kurmak, Edremit kampının temel gereksinimlerindendir.",
      "Kazdağı Hasanboğuldu patikası sabah erken başlanmalı; Altınoluk sahil kampı ve Antandros antik kent kalıntıları aynı gün birleştirilebilir. Edremit Havalimanı 15 dakika mesafededir.",
    ],
  },
  "balikesir/ayvalik": {
    paragraphs: [
      "Ayvalık kamp deneyimi ana karada mı Cunda Adası'nda mı geçeceği sorusuyla başlar. Cunda'ya feribot veya köprü ile geçilir; adada Taksiyarhis çevresi dar sokakları ve park kısıtı nedeniyle kamp ekipmanı taşımayı zorlaştırabilir. Şeytan Sofrası seyir terasından Midilli (Lesbos) Adası silueti net seçilir; gün batımı için araçla çıkış planlanmalıdır. Sarımsaklı Plajı geniş kumsalı ve tesis altyapısıyla ana karadaki en erişilebilir kamp noktasıdır; Cunda ise taş ev atmosferi ve küçük koylarıyla daha butik bir deneyim sunar. İki seçenek arasındaki fark, ulaşım kolaylığı ile ada romantizmi arasında bir tercih gerektirir. Cunda feribot saatleri gece dönüşünü doğrudan belirler.",
      "Kasım ayında zeytin hasatı tüm yarımadayı hareketlendirir; hasat döneminde kırsal yollarda işçi ve traktör trafiği artar. Cunda'da kamp alanı sınırlıdır; yaz sezonunda önceden rezervasyon şarttır. Ayvalık merkezdeki zeytinyağı atölyeleri ve balık restoranları kamp rotasına gastronomi katmanı ekler; ancak ada feribot saatleri gece dönüşünü belirler. Mayıs-haziran ve eylül ayları, yaz kalabalığından uzak hem deniz hem kamp açısından en dengeli dönemlerdir. Zeytinlik arazilerine izinsiz girilmemesi, Ayvalık'ın sürdürülebilir kamp geleneğinin temel gereksinimlerindendir.",
      "Cunda feribotu yaz sezonunda saatlik sefer yapar; Şeytan Sofrası gün batımı için 18:00 öncesi varış önerilir. Midilli (Lesbos) feribotu Ayvalık iskelesinden kalkar; ada kampı için pasaport gereklidir.",
    ],
  },
  "antalya/kas": {
    paragraphs: [
      "Kaş kamp rotasının klasik üçlüsü Kekova batık şehir turu, Kaputaş Plajı molası ve Meis Adası manzaralı akşam yemeğidir. Üçağız'dan kalkan tekne turları batık kalıntıları yakından gösterir; kamp programına yarım gün ayırmak yeterlidir. Likya Yolu'nun Kaş-Kalkan arası etabı deniz manzaralı patikalar sunar; çok günlük yürüyüş planlayanlar su noktalarını önceden haritalamalıdır. Kaş'ta dalış merkezleri yoğundur; sabah dalış, öğleden sonra koy kampı kombinasyonu yaz aylarında popülerdir. Meis Adası'nın beyaz evleri, Kaş limanından gece boyunca net görülür. Likya Yolu üzerinde su ve gıda planlaması, çok günlük trekking programlarının temelini oluşturur.",
      "Kaputaş'a araç parkı sınırlıdır; yaz ortasında sabah erken saatte varış şarttır. Meis'e günübirlik feribot seferleri Kaş limanından kalkar; pasaport gerekliliği kamp planına dahil edilmelidir. Nisan-mayıs ve ekim ayları hem Likya patikalarındaki sıcaklık hem de dalış görüş mesafesi açısından idealdir; temmuz-ağustos'ta koy kampında gölge aramak zorunlu hale gelir. Patara kumulları ve antik tiyatro, Kaş kamp rotasına günübirlik keşif durakları ekler. Yamaç yollarında araç güvenliği ve deniz ile dağ arasındaki sıcaklık farkına göre katmanlı giyinmek, Kaş kampının temel gereksinimlerindendir.",
      "Üçağız'dan Kekova tekne turu yarım gün sürer; Kaputaş merdivenleri sabah 08:00 öncesi tenha kalır. Meis günübirlik feribotu pasaport ve sabah seferi planlaması gerektirir.",
    ],
  },
  "antalya/kalkan": {
    paragraphs: [
      "Kalkan'ın teraslı beyaz evleri koy manzarasına bakan yamaçlarda konumlanır; kamp alanları genellikle limanın güneyindeki koylarda veya Bezirgan Yaylası yönündedir. Kaputaş Plajı Kalkan'a on beş dakikalık mesafededir ancak park ve erişim yaz aylarında zorlaşır; kamp gününe erken sabah ziyareti eklemek mantıklıdır. Patara antik kenti ve kumulları Caretta caretta alanı olduğundan gece kamp kuralları sıkıdır; ışık kirliliğinden kaçınılmalıdır. Kalkan limanından gün batımı manzarası, teraslı yapıların siluetiyle birleşerek Akdeniz'in en fotojenik anlarından birini sunar. Dar ve dik yamaç yollarında dikkatli araç kullanmak, Kalkan kamp rotasının güvenlik gereksinimlerindendir.",
      "Bezirgan Yaylası yaz ortasında serinlik sunar; kıyı kampından yayla gezisine geçişte sıcaklık farkı on dereceyi bulabilir. Kalkan koylarında küçük ölçekli tesisler ağırlıktadır; büyük karavan parkı seçeneği sınırlıdır. İslamlar köyü sakin atmosferiyle Kalkan merkez kalabalığından uzaklaşmak isteyenlere alternatif oluşturur. Mayıs ve eylül ayları hem deniz suyu sıcaklığı hem de kamp alanı müsaitliği açısından altın dönem kabul edilir. Yayla yollarında erken kar riskine karşı hazırlıklı olmak, sonbahar kamp programları için önem taşır.",
      "D400 Kaş-Kalkan bağlantısı ilçenin ana arteridir; Kaputaş 15 dakika, Patara 20 dakika mesafededir. Mayıs-eylül kıyı-yayla kombinasyonu ideal kamp penceresidir. Bezirgan Yaylası'ndan Xanthos vadisine uzanan patika, çok günlük Likya rotalarının Kalkan çıkışlı varyantlarında kamp molaları için kullanılır.",
    ],
  },
  "antalya/olympos": {
    paragraphs: [
      "Olympos Vadisi'nde kamp alanları antik kent kalıntıları ile çam ormanının iç içe geçtiği dar bir şeritte sıralanır. Çıralı sahili Caretta caretta yumurtlama alanı olduğundan gece plajda ışık kullanımı kısıtlıdır; kırmızı filtreli fener tercih edilmelidir. Yanartaş'a gece yürüyüşü vadi kampının ayrılmaz parçasıdır; patika taşlık ve karanlıktır, el feneri şarttır. Antik tiyatro ve liman kalıntıları arasında kurulan çadır, Olympos'u Türkiye kamp deneyiminin en ikonik adreslerinden biri yapar. Antik sit alanı kurallarına uymak ve kaplumbağa koruma dönemlerinde ışık kısıtlamalarını takip etmek zorunludur. Yanartaş ziyareti gece kamp deneyimine mistik bir katman ekler.",
      "Vadi içinde bisiklet kiralama yaygındır; antik liman, tiyatro ve nehir yatağı arasında dolaşmak kamp gününü zenginleştirir. Yaz aylarında genç gezgin yoğunluğu artar; mayıs ve eylül ayları daha sakin bir orman kampı ortamı sağlar. Olympos girişinde araç park edilir; vadide yürüyerek ulaşım esastır, tekerlekli bavul pratik değildir. Ağaç ev ve bungalov tesisleri, çadır kampına alternatif konaklama seçenekleri sunar. Vadi yollarında bisiklet ve yaya trafiğine dikkat etmek, Olympos kampının temel güvenlik gereksinimlerindendir.",
      "Antalya-Finike yolu Olympos çıkışında; Çıralı sahili yürüyüşle 20 dakika. Mayıs-haziran kaplumbağa sezonu öncesi, eylül Caretta koruma dönemi kuralları geçerlidir.",
    ],
  },
  "artvin/yusufeli": {
    paragraphs: [
      "Yusufeli kamp rotası Çoruh Nehri kıyısı, Barhal köyü patikaları ve Kaçkar trekking çıkış noktaları üzerinden şekillenir. Çoruh'ta ilkbahar-sonbahar rafting sezonu yoğundur; nehir kenarı kamp kurarken su debisi ve gece yağmur tahmini mutlaka kontrol edilmelidir. Barhal, eski yerleşim yeri ve taş köprüleriyle vadinin en fotojenik duraklarından biridir; Kaçkar zirve rotalarına çıkış birçok trekking programı buradan başlar. Erzurum Havalimanı yaklaşık iki buçuk saat mesafededir; uçakla gelenler için en pratik giriş kapısıdır. Tekkale köyü ve çevresindeki patikalar, çok günlü dağ kampı programlarının temelini oluşturur.",
      "Yayla sezonu genellikle haziran sonundan eylüle kadar sürer; bu dönemde yüksek ırmak geçişleri ve gece sıcaklığı düşüşleri ekipman seçimini belirler. Yusufeli'de gece sıcaklığı rakıma göre hızla düşer; üç mevsim uyku tulumu ve su geçirmez dış katman temel gereksinimlerdir. Vadide telefon çekimi sınırlı alanlar vardır; uzun trekking programlarında uydu haberleşme cihazı veya acil plan paylaşımı önerilir. Çoruh'un coşkulu suları ve dik yamaçlar, deneyimli kampçılara zorlu ama ödüllendirici bir macera ortamı sunar.",
      "Erzurum Havalimanı 2 saat mesafededir; Demirkent yolu Kaçkar patikalarına bağlanır. Barhal rafting sezonu nisan-ekim; yağmur sonrası nehir debisi dere kenarı kampını tehdit eder. Altiparmak Dağları eteklerindeki tesisler, nehir kenarı kampı ile yüksek rakım trekking çıkışını aynı hafta sonu programında birleştirmek isteyen macera gruplarına hitap eder.",
    ],
  },
  "bolu/mudurnu": {
    paragraphs: [
      "Mudurnu, Yedigöller yolunun tarihî ara durağı olarak Osmanlı sokak dokusunu kamp rotasına taşır. İlçe merkezindeki ahşap evler ve taş camiler günübirlik yürüyüş rotası oluşturur; Babas Deresi çevresindeki orman alanları ise merkeze yakın doğa kampı imkânı sunar. Yedigöller Milli Parkı giriş kuyrukları hafta sonları uzayabilir; Mudurnu'da geceleyip sabah erken parka giriş stratejik avantaj sağlar. Osmanlı döneminden kalma taş sokaklar, kamp öncesi veya sonrası kısa bir tarihî keşif imkânı sunar. Tarihî evlere ve cami çevresine saygılı davranmak, Mudurnu kamp deneyiminin kültürel boyutunu tamamlar.",
      "Sonbahar yaprak dökümü Mudurnu ormanlarını altın ve kızıla boyar; bu dönem fotoğraf ve kamp için en görkemli mevsimdir. Kış aylarında kar yağışı yolları kapatabilir; zincir veya kış lastiği taşınmalıdır. Mudurnu'da organize kamp alanı sayısı sınırlıdır; çoğu ziyaretçi Yedigöller'e yakın piknik-kamp alanlarını veya köy yakınındaki belirlenmiş noktaları tercih eder. Orman yangını riskine karşı açık ateş kurallarına sıkı uyulmalı; taşınabilir ocak güvenli alternatif sunar. Yedigöller giriş kuyruklarını plana dahil etmek, hafta sonu kamp programları için kritik bir adımdır.",
      "D-100 Mudurnu çıkışı Yedigöller yoluna bağlanır; İstanbul 2,5 saat mesafededir. Ekim-kasım yaprak dökümü altın sezon, ocak-şubat kar kampı dönemidir.",
    ],
  },
};
