export const provinceSupplementContent: Record<string, { paragraphs: string[] }> = {
  izmit: {
    paragraphs: [
      "Kocaeli'nin İzmit merkezi, TEM otoyolu ve yüksek hızlı tren hattı sayesinde İstanbul ile Ankara arasındaki kamp rotalarının kavşak noktasıdır. Sapanca Gölü'nün kuzey kıyısındaki çam ormanları, Maşukiye derelerinin gölge vadileri ve Kartepe'nin yaz aylarında açılan yamaç alanları hafta sonu çadır kurulumu için en çok tercih edilen duraklardır. Samanlı Dağları'nın doğu yamaçlarında ise karavan parkları ve bungalov tesisleri, şehir gürültüsünden bir saat uzaklıkta konaklama imkânı sunar.",
      "Kartepe'de kış sonrası mayıs-haziran döneminde kar eriyişiyle birlikte yeşeren çimenliklerde kamp kurulabilir; yazın ise göl kenarındaki Kırkpınar ve Poyrazlar sahil şeridinde rüzgârlı ama serin geceler yaşanır. İzmit Körfezi boyunca Dilovası'ndan Karamürsel'e uzanan kıyı şeridinde balıkçı barınakları çevresindeki sakin koylar, deniz manzaralı kamp için alternatif oluşturur. Marmara ikliminin nemli yaz gecelerinde çadır havalandırması ve yağmur örtüsü taşımak konforu belirgin şekilde artırır.",
      "Kocaeli ulaşım ağı, İstanbul-Ankara eksenindeki kampçılar için doğal bir dağıtım merkezi işlevi görür: YHT İzmit istasyonundan Sapanca'ya aktarmalı servisler, TEM otoyolunun Kartepe ve Maşukiye çıkışları ve D-100 kıyı şeridi aynı hafta sonu içinde farklı kamp tiplerine erişim sağlar. Mevsim matrisi belirgindir: ocak-şubat Kartepe kar kampı, mart-nisan orman nem sezonu, mayıs-haziran göl kenarı ideal dönem, temmuz-ağustos kıyı meltemi ve yoğun trafik, eylül-ekim sonbahar yaprakları ve en dengeli sıcaklıklar. Kartepe-Sapanca-Maşukiye üçgeni tek gece konaklamayla üç farklı mikroklimayı deneyimlemek isteyenler için en verimli yerel rota olarak planlanabilir.",
      "Sapanca, Kartepe ve Maşukiye üç kamp bölgesi birbirinden belirgin ayrılır: göl kenarı nemli ve sivrisinek yoğun, Kartepe rüzgârlı ama kuru uyku sunar, Maşukiye ise dere kenarında en güvenli zemin ve suya yakınlık sağlar. Hafta sonu TEM çıkışında cumartesi sabah 06:00 öncesi varış, Sapanca giriş kuyruğunu ciddi ölçüde kısaltır; karavanlı gruplar Kartepe yamaç parklarını, çadırlı aileler Maşukiye derelerini tercih etmelidir.",
    ],
  },
  canakkale: {
    paragraphs: [
      "Gökçeada ve Bozcaada feribot iskelelerinden adalara geçen kampçılar, rüzgârlı batı kıyıları ile korunaklı doğu koyları arasında farklı deneyimler yaşar. Gökçeada'da Aydıncık Plajı çevresindeki kum tepeleri gece kampı için geniş alan sunarken, Bozcaada'da bağ yollarının arasındaki zeytin gölgelerinde yaz akşamları serin kamp kurulabilir. Ana karada Assos Behramkale'nin antik limanı manzaralı yamaçları, rüzgâr yönüne göre çadır konumlandırmayı zorunlu kılan Ege kıyısının en rüzgârlı noktalarından biridir.",
      "Kabatepe sahilinde Gelibolu Yarımadası Tarihi Milli Parkı'na yakın konum, sabah erken saatlerde anıt ziyaretini kamp programına eklemeyi mümkün kılar. Kaz Dağı eteklerindeki Hasanboğuldu ve Sütüven şelaleleri çevresindeki orman içi alanlar, yaz sıcağından kaçmak isteyenler için serin alternatifler barındırır. Biga Yarımadası'nda Lapseki feribot hattına yakın kıyı noktaları, Ege ile Marmara arasında geçiş yapan karavan rotalarının mola kampı olarak kullanılır; ada seferlerinde araç rezervasyonu yaz sezonunda haftalar öncesinden dolduğundan ulaşım planı kamp takviminin merkezinde yer almalıdır.",
      "Çanakkale feribot ağı kamp rotasının bel kemiğidir: Eceabat-Kabatepe hattı Gelibolu ve Gökçeada'ya, Geyikli-Bozcaada hattı ada kampına, Lapseki-Çardak ise Marmara geçişine bağlanır. Mevsim planlaması ada ve ana kara arasında ayrılır: nisan-mayıs badem çiçeği ve sakin koylar, haziran-ağustos meltem ve feribot kuyrukları, eylül-ekim üzüm hasadı ve Assos gün batımı, kasım-mart rüzgârlı ama tenha kıyılar. Ana karada Assos-Kaz Dağı-Gelibolu üçlüsü, adalarda ise Gökçeada kuzey-delta ile Bozcaada bağ yolları rotası iki günde tamamlanabilecek en otantik yerel kamp halkasını oluşturur.",
      "Üç günlük ideal rota cumartesi Assos Behramkale'de rüzgâra göre konumlanmış gece kampı, pazar Geyikli feribotuyla Bozcaada bağ yollarında ikinci gece ve pazartesi sabah Kabatepe üzerinden Gelibolu anıt ziyaretiyle tamamlanır. Ada seferlerinde araç rezervasyonu yazın haftalar öncesinden dolar; ana karada Kaz Dağı şelaleleri gündüz aktivitesi, gece kampını Assos veya Gökçeada kuzey koylarında planlamak en dengeli programı oluşturur.",
    ],
  },
  istanbul: {
    paragraphs: [
      "Belgrad Ormanı'nın 55 bin hektarlık çam örtüsü, İstanbul'un Avrupa yakasında en geniş orman kamp alanını oluşturur; Atatürk Arboretumu yakınındaki piknik alanlarından Sultanbeyli orman girişlerine kadar uzanan şerit, şehir sınırı içinde çadır kurulabilecek nadir yeşil koridorlardan biridir. Anadolu yakasında Şile sahilinde kumsal kampı, Ağva'da Yeşilçay ve Göksu derelerinin birleştiği delta bölgesinde nehir-ağız kampı farklı deneyimler sunar.",
      "Polonezköy Tabiat Parkı'nda organize çadır alanları ve karavan parkları mevcutken, Kilyos ve Riva kıyılarında rüzgârlı yaz gecelerinde sağlam kazık ve gerdirme şarttır. İlkbahar aylarında orman zemininde nem birikimi yoğun olduğundan yüksek tabanlı mat tercih edilmeli; sonbaharda ise Belgrad Ormanı'ndaki meşe yaprakları zemini yumuşak bir tabaka haline getirir. Hafta sonları TEM ve Kuzey Marmara Otoyolu trafiği sabah erken saatlerde çıkış yapmayı zorunlu kılar; metro ve otobüsle ulaşılabilen orman girişleri araçsız kampçılar için pratik alternatif oluşturur.",
      "İstanbul'da ulaşım hub seçimi kamp tipini belirler: M2 hattı son duraklardan Belgrad Ormanı'na, Marmaray ve İDO ile Şile-Ağva kıyısına, otobüs hatlarıyla Polonezköy'e araçsız erişim mümkündür. Mevsim matrisi kıyı-orman arasında keskin ayrılır: mart-nisan orman çiçeklenmesi, mayıs-haziran Ağva'da nehir-ağız kampı, temmuz-ağustos Şile'de kumsal ve yoğun trafik, eylül-ekim Belgrad'da sonbahar yürüyüşü. Şile-Riva-Ağva kıyı şeridi tek hafta sonunda kumsal kampı ile nehir deltası deneyimini birleştiren en pratik yerel rota olarak planlanabilir; Cuma akşamı metro-otobüs kombinasyonu trafik stresini minimize eder.",
      "Belgrad Ormanı, Şile kıyısı ve Ağva deltası aynı il içinde üç farklı kamp karakterini temsil eder: orman nemli ve sivrisinek yoğun, Şile rüzgârlı kumsalda sağlam kazık ister, Ağva ise nehir ağzında daha sakin ama yazın kalabalıktır. Araçsız kampçılar cumartesi sabah M2 ile Belgrad'a, pazar İDO ile Şile-Ağva hattına geçerek iki geceyi farklı mikroklimalarda geçirebilir; yağmur örtüsü her üç bölgede de zorunlu ekipmandır.",
    ],
  },
  bursa: {
    paragraphs: [
      "Uludağ Milli Parkı'nın 1800 metre üzerindeki Zirve ve Sarıalan bölgeleri, yaz aylarında trekking kampları için Türkiye'nin en eski dağ turizmi rotalarından birini sunar. Mudanya'nın tarihi iskele çevresinden Zeytinbağı sahiline, Gemlik körfezinin zeytinlik yamaçlarından Orhangazi Gölü kıyısındaki sakin koylara uzanan güney şerit, aynı gün içinde dağ ve deniz kampını birleştirmeyi mümkün kılar. İznik Gölü'nün kuzey kıyısındaki Roma surları manzaralı alanlar, göl kenarı kampının en sakin alternatiflerini barındırır.",
      "Uludağ eteklerinde Cumalıkızık köy yolu boyunca konaklama birleşik tesisler, Osmanlı kırsal mimarisini kamp rotasına dahil eder. Kış aylarında Uludağ'da kar kampı yapılırken, ilkbahar erken döneminde Bursa-Osmaneli arasındaki orman yollarında reçine kokulu çam ormanlarında çadır kurulabilir. Yazın Mudanya kıyısında nem oranı yükselir; dağ-kıyı arasındaki 800 metrelik rakım farkı aynı gün içinde 10 derecelik sıcaklık değişimi yarattığından katmanlı ekipman taşınması şarttır. Teleferik hattına yakın alanlarda hafta sonu yoğunluğu erken varış saatini gerektirir.",
      "Bursa-Osmanlı yolu (D-575) dağ kampına, Mudanya iskele yolu kıyı kampına, İznik gölü çevresi ise sakin göl kenarı alternatifine bağlanır; Bursa şehir içi metro hattı Uludağ teleferik istasyonuna aktarmalı ulaşım sunar. Mevsim döngüsü belirgindir: aralık-mart Uludağ kar ve teleferik, nisan-mayıs Cumalıkızık ve orman çiçekleri, haziran-ağustos Mudanya kıyısı nemli geceler, eylül-ekim İznik Gölü sonbahar sessizliği. Uludağ zirve-Mudanya kıyısı-İznik Gölü üçgeni aynı hafta sonu içinde dağ, deniz ve göl kampını birleştiren Bursa'nın en karakteristik yerel rotasıdır.",
      "Uludağ, Mudanya kıyısı ve İznik Gölü aynı hafta sonunda karşılaştırıldığında belirgin farklar ortaya çıkar: dağ geceleri serin ve rüzgârlı, kıyı nemli ama deniz manzaralı, İznik ise en sakin ve düz zemin sunar. Cumartesi sabah teleferikle Uludağ'da gece kampı, pazar öğleden sonra Mudanya kıyısında mola ve akşam İznik'te son gece planı, 800 metrelik rakım farkını ekipman listesine yansıtmayı zorunlu kılar.",
    ],
  },
  tekirdag: {
    paragraphs: [
      "Şarköy ve Mürefte bağları arasındaki toprak yollar, yaz hasat döneminde üzüm kokulu gölge alanlarda kamp kurmak isteyenlere benzersiz bir peyzaj sunar. Marmara Ereğlisi sahilinde kumsal kampı, Hoşköy limanı çevresinde balıkçı teknelerinin demirlediği kıyı şeridi deniz manzaralı alternatifler oluşturur. Ergene Deltası'nın kuş göç yolu üzerindeki sulak alanları, ilkbahar ve sonbahar aylarında göçmen türleri gözlemlerken kamp yapmayı birleştiren doğa tutkunlarına hitap eder.",
      "Istranca Dağları'nın Tekirdağ sınırındaki giriş kesimlerinde yoğun fıstık çamı ormanları, yaz ortasında bile serin geceler sağlar. Kıyı boyunca esen poyraz rüzgârı, Şarköy sahillerinde çadır kurulumunu zorlaştırdığından rüzgâr kırıcı doğal setler aranmalıdır. Bağ boğumları döneminde (temmuz-ağustos) bağ sahiplerinin izni olmadan özel arazilere girilmemesi yerel yaşamın sürekliliği açısından kritiktir. İstanbul'dan TEM otoyoluyla iki saatlik mesafe, Cuma akşamı çıkışlı kısa kamp kaçamaklarını pratik kılar.",
      "Tekirdağ, İstanbul'un batı kapısı olarak TEM otoyolu ve D-110 kıyı şeridiyle Şarköy-Mürefte bağ rotasına, Ergene Deltası kuş gözlem noktalarına ve Istranca orman girişlerine dağıtım sağlar. Mevsim matrisi bağ ve kıyı odaklıdır: nisan-mayıs kuş göçü ve delta sulak alanları, haziran-ağustos üzüm bağları gölgesi ve poyraz rüzgârı, eylül hasat kokusu ve tenha kıyılar, kasım-mart sakin Şarköy sahilleri. Şarköy bağ yolları-Mürefte kıyısı-Hoşköy limanı halkası, tek gecelik kamp programında bağ manzarası ile deniz kenarı molasını birleştiren en otantik Tekirdağ rotasıdır.",
      "Şarköy kıyısı, Mürefte bağları ve Istranca orman girişleri üç farklı kamp profili sunar: sahil poyraza açık ve çadır kurulumu zor, bağ yolları gölge ama özel mülkiyet sınırlarına dikkat gerektirir, Istranca ise yaz ortasında bile serin uyku sağlar. Temmuz-ağustos hasat döneminde bağ sahiplerinden izin almadan araziye girilmemeli; kıyı kampında rüzgâr kırıcı doğal setler mutlaka aranmalıdır.",
    ],
  },
  izmir: {
    paragraphs: [
      "Foça'nın Sazlıca ve Yenifoça koyları, Çeşme Yarımadası'nın Ildırı antik kent kalıntıları ve Alaçatı rüzgâr sörfü sahilleri, Ege'nin farklı kamp tiplerini aynı il sınırları içinde sunar. Seferihisar Sığacık kale surları içindeki taş evlerin gölgesinde kamp kurulabilen nadir kıyı noktaları, Cittaslow ilçenin yavaş yaşam ritmine uyum gerektirir. Dikili ve Bergama yönünde Kazdağı eteklerine doğru yükselen yamaçlarda zeytinlikler arasındaki düzlükler, deniz manzaralı yüksek rakım kampı imkânı verir.",
      "Urla yarımadasındaki bağ evleri arasındaki gizli koylar, yazın kalabalık Çeşme rotasına alternatif oluşturur. Karaburun Yarımadası'nda rüzgâr türbinlerinin bulunduğu açık alanlar gece yıldız gözlemi için idealdir ancak rüzgâr kesici bulunmaz. Mayıs-haziran döneminde Ege suyu henüz soğukken kıyı kampı için gün ortası yüzme yerine akşam ve sabah aktiviteleri planlanmalıdır. İzmir-Adnan Menderes Havalimanı'na yakınlık, uçakla gelen kampçıların kıyı ilçelerine kısa sürede ulaşmasını sağlar.",
      "Adnan Menderes Havalimanı Ege kampının ana hub'ıdır: otoyol ile Çeşme'ye 45 dakika, Urla'ya 25 dakika, Dikili-Kazdağı yönüne 90 dakika mesafe sunar. Mevsim planlaması kıyı boyunca değişir: nisan-mayıs mandalina çiçeği ve ılık geceler, haziran-ağustos meltem ve yoğun Çeşme trafiği, eylül-ekim bağ hasadı ve sakin Foça koyları. Foça-Sığacık-Urla-Çeşme kıyı halkası uçakla gelenler için dört farklı kamp karakterini (Cittaslow liman, antik kent, bağ-koy, rüzgâr sörfü) tek haftada birleştiren İzmir'in imza rotasıdır.",
      "Dört günlük İzmir kıyı rotası cumartesi Foça'da sakin koy kampı, pazar Sığacık surları içinde tarihî atmosfer, pazartesi Urla bağ-koy geçişi ve salı Çeşme-Alaçatı melteminde son gece olarak planlanabilir. Çeşme kalabalık ve rüzgârlı, Foça tenha ama suya uzak koylar var, Urla ise ikisinin arasında en dengeli seçenektir; havalimanından kiralık araç tüm duraklara iki saat içinde ulaşım sağlar.",
    ],
  },
  mugla: {
    paragraphs: [
      "Datça Yarımadası'nın Knidos antik limanı ile Palamutbükü arasındaki 70 kilometrelik kıyı şeridi, Ege ile Akdeniz'in birleştiği noktada rüzgârlı ama berrak sularda kamp imkânı sunar. Gökova Körfezi'nde Akyaka Azmak Nehri ağzı, tatlı-su ile tuzlu suyun karıştığı nadir ekosistemlerden birinde kamp kurulmasına olanak tanır. Bozburun Yarımadası'nda Selimiye ve Bozburun köyleri arasındaki korunaklı koylar, yat trafiğinden uzak sakin kamp noktaları barındırır.",
      "İç kesimlerdeki Gökova Dağları'nda çam ormanları, kıyıdaki 35 derecelik yaz sıcaklığından 15 derece daha serin geceler sağlar. Marmaris-Bozburun karayolu boyunca dar virajlar karavan erişimini sınırlar; çadır kampı bu bölgelerde daha yaygındır. Eylül sonunda kıyı su sıcaklığı hâlâ yüzmeye elverişliyken kalabalık azalır ve Likya Yolu'nun Fethiye kesimindeki trekking kampları birbirine bağlanabilir. Ölüdeniz yamaç paraşütü iniş bölgesine yakın alanlarda hava trafiği sabah erken saatlerde yoğunlaşır.",
      "Dalaman Havalimanı Muğla kampının güney hub'ıdır; Datça'ya 2,5 saat, Fethiye'ye 45 dakika, Marmaris'e bir saat mesafe sunar. Mevsim matrisi kıyı-iç kesim ayrımıyla okunur: nisan-mayıs badem çiçeği ve Likya patika ideal sıcaklığı, haziran-ağustos meltem ve koy kalabalığı, eylül-ekim deniz suyu ılıklığı ve tenha patikalar. Datça Knidos-Fethiye Kabak-Likya Yolu-Olympos hattı çok günlük trekking ve kıyı kampını birleştiren Muğla'nın en prestijli ulaşım-kamp koridorudur; araçsız yürüyüşçüler Fethiye-Olympos arası servis bağlantılarıyla rotayı tamamlayabilir.",
      "Datça, Fethiye ve Marmaris aynı il sınırlarında farklı kamp deneyimleri sunar: Datça rüzgârlı ama tenha, Fethiye Likya patikalarıyla trekking odaklı, Marmaris koyları kalabalık ama ulaşım kolaydır. Beş günlük rota Datça Knidos'ta başlayıp Akyaka Azmak'ta nehir ağzı molası, Kabak koyunda trekking gecesi ve Olympos antik kentte final kampıyla tamamlanır; iç kesim Gökova Dağları yazın kıyıya göre on beş derece daha serindir.",
    ],
  },
  balikesir: {
    paragraphs: [
      "Kazdağı Milli Parkı'nın Hasanboğuldu ve Sütüven şelaleleri arasındaki orman patikaları, İda Dağları'nın mitolojik atmosferinde 800-1200 metre rakımlarda çadır kampı için Türkiye'nin en değerli yeşil alanlarından birini oluşturur. Ayvalık merkezinden Cunda Adası'na uzanan causeway üzerindeki tuzlu su kanalları manzarası, adada Taş Kahve çevresindeki taş evlerin gölgesinde kamp programına tarihî doku katar. Edremit Körfezi'nin Altınoluk ve Akçay sahillerinde zeytinlik yamaçlarının denizle buluştuğu noktalar, gün batımı kampının en fotojenik adreslerindendir.",
      "Kazdağı zirvesine çıkan 17 kilometrelik patika rotası boyunca belirlenmiş çok günlük kamp noktaları, deneyimli trekking kampçılarını hedefler; giriş kapısından itibaren araç trafiği kısıtlı olduğundan ekipman sırt çantasıyla taşınmalıdır. Ayvalık-Adalar bölgesindeki Sakız Adası feribot seferleri yaz sezonunda saatlik planlanır ve ada kampında su kaynağı sınırlıdır. Edremit ovasından antik Adramytteion kalıntılarına uzanan kıyı şeridinde rüzgâr enerjisi santralleri gece kampında sürekli hafif uğultu yaratır. İlkbahar aylarında Kazdağı eteklerinde endemik Çanakkale geveni çiçek açar; sonbaharda ise meşe ormanları altın rengine bürünerek farklı mevsim deneyimleri sunar.",
      "Balıkesir kamp ulaşımı üç koridora ayrılır: Kazdağı Milli Parkı giriş kapısı (Altınoluk-Edremit yolu) orman kampına, Ayvalık feribot iskelesi Cunda ve Midilli bağlantısına, Edremit Havalimanı ve otoban çıkışı ise zeytin körfezi kıyı şeridine dağıtım sağlar. Mevsim matrisi belirgindir: nisan-mayıs endemik çiçek ve serin orman, haziran-ağustos körfez meltemi ve feribot kuyrukları, eylül-ekim zeytin hasadı kokusu, kasım-mart tenha kıyılar. Kazdağı Hasanboğuldu girişi-Edremit körfezi kıyı kampı-Ayvalık Cunda feribot halkası, aynı hafta sonu içinde dağ ormanı ile Ege adaları atmosferini birleştiren Balıkesir'in imza rotasıdır.",
      "Kazdağı zirve patikasında çok günlük kamp planlayanlar ekipmanı sırt çantasıyla taşımalı; araç trafiği park girişinden itibaren kısıtlıdır. Ayvalık-Cunda hattında ada kampında su kaynağı sınırlı olduğundan günlük en az beş litre kişi başı stok şarttır. Edremit körfezi kıyısında rüzgâr türbinlerinin gece uğultusu hafif sürekli gürültü yaratır; hassas uyuyanlar orman tarafını tercih etmelidir.",
    ],
  },
  aydin: {
    paragraphs: [
      "Dilek Yarımadası-Büyük Menderes Deltası Milli Parkı'nın Davutlar girişinden Aydınlık koyuna uzanan 20 kilometrelik patika, aynı gün içinde orman, dağ ve deniz kampını birleştiren nadir rotalardan biridir. Arapapıştı Kanyonu'nun 380 basamaklı merdivenle inilen tabanında serin hava akımı, yaz ortasında bile 15 derece civarında sıcaklık sağlar. Kuşadası Güvercinada kale surları manzaralı kıyı şeridi, Ege'nin en tanınmış gece kampı noktalarından birine dönüşmüştür.",
      "Büyük Menderes Deltası'nda ilkbahar göç döneminde flamingo ve pelikan gözlemi kamp programına entegre edilebilir; delta alanlarında gece kampı yasak bölgeler bulunduğundan park yönetimi kuralları önceden incelenmelidir. Didim Altınkum sahili yaz aylarında yoğunken, Didim'in kuzeyindeki Milet antik limanı çevresindeki zeytinlikler daha sakin alternatif sunar. Nazilli-Sultanhisar arasındaki iç ova yollarında gece sıcaklığı yazın 25 derecenin üzerine çıkar; kanyon ve milli park alanları ova sıcaklığından en az 8 derece daha serindir.",
      "Aydın-Nazilli otoban çıkışı Dilek Yarımadası Milli Parkı girişine, Kuşadası bağlantı yolu kıyı kampına, Söke üzerinden Büyük Menderes Deltası kuş gözlem noktalarına dağıtım sağlar. Mevsim matrisi delta-kanyon-kıyı üçgeninde okunur: mart-nisan flamingo göçü, mayıs-haziran Arapapıştı serinliği, temmuz-ağustos Didim kalabalığı ve ova sıcağı, eylül-ekim delta sulak alanları ve tenha koylar. Dilek Yarımadası Davutlar girişi-Arapapıştı Kanyonu-Milet antik limanı halkası, aynı gün içinde orman, kanyon ve tarih duraklarını birleştiren Aydın'ın en verimli yerel kamp rotasıdır.",
      "Dilek Yarımadası, Arapapıştı Kanyonu ve Didim kıyısı üç bölge arasında seçim yaparken sıcaklık farkı belirgindir: milli park yazın ova sıcağından sekiz derece serin, kanyon tabanı on beş dereceye kadar düşer, Didim ise en sıcak ama denize en yakın seçenektir. İki günlük program cumartesi Davutlar patikasında gece kampı, pazar sabah Arapapıştı merdiven inişi ve öğleden sonra Milet antik limanı ziyaretiyle tamamlanır.",
    ],
  },
  manisa: {
    paragraphs: [
      "Spil Dağı Milli Parkı'nın 1500 metre rakımlı Nallıhan seyir terasından Manisa ovasına bakan manzara, çam ormanları içindeki belirlenmiş kamp alanlarında gün doğumu fotoğrafçılığı için eşsiz bir perspektif sunar. Gölmarmara Gölü kıyısındaki sazlık alanlar, yaz aylarında kuş cılıtı eşliğinde göl kenarı kampı imkânı verir. Sardes antik kentinin Artemis Tapınağı kalıntıları yakınındaki Gediz ovası, tarih ve kamp rotasını birleştiren kültür durakları oluşturur.",
      "Demirci ve Gördes yaylalarına çıkan virajlı dağ yolları, temmuz-ağustos döneminde yayla şenlikleriyle canlanır; bu dönemde yerel çobanların bilgisi su kaynağı ve hava koşulları açısından değerlidir. Spil Dağı'nda gece sıcaklığı yazın bile 10 dereceye düşebilir; ova sıcaklığıyla arasındaki 20 derecelik fark katmanlı giyim zorunluluğu yaratır. Salihli yakınındaki Bintepe (Alyattes) höyüğü çevresindeki tarım arazileri arasında kamp kurulabilecek açık alanlar sınırlıdır ve özel mülkiyet sınırlarına dikkat edilmelidir.",
      "Manisa, İzmir'e bağlı D-565 ve otoban çıkışlarıyla Spil Dağı Milli Parkı girişine, Salihli yönüyle Sardes antik kentine ve Demirci yoluyla yayla kamp alanlarına dağıtım sağlar. Mevsim matrisi ova-dağ farkını vurgular: nisan-mayıs Gölmarmara kuş cılıtı, haziran-ağustos yayla şenlikleri ve Spil serinliği, eylül-ekim üzüm hasadı, kasım-mart ova sisi ve tenha patikalar. Spil Dağı Nallıhan seyir terası-Gölmarmara Gölü kıyısı-Sardes antik kent halkası, tek hafta sonunda dağ ormanı, göl kenarı ve arkeolojik durakları birleştiren Manisa'nın imza rotasıdır.",
      "Spil Dağı, Gölmarmara Gölü ve Demirci yaylaları farklı kamp profilleri sunar: Spil serin ama gece on dereceye düşer, göl kıyısı düz zemin ve kuş sesiyle sakin, yaylalar temmuz-ağustosta şenlik nedeniyle kalabalıktır. Ova ile dağ arasındaki yirmi derecelik sıcaklık farkı katmanlı giyim zorunluluğu yaratır; yayla döneminde yerel çobanlardan su kaynağı bilgisi almak pratik avantaj sağlar.",
    ],
  },
  antalya: {
    paragraphs: [
      "Likya Yolu'nun Adrasan'dan Gelidonya Feneri'ne uzanan 30 kilometrelik kesimi, antik kalıntılar ve korunaklı koylar arasında çok günlük trekking kampları için Türkiye'nin en prestijli rotasını oluşturur. Olympos antik kentinin çam ağaçları arasındaki çadır alanları, yanında akan nehir sesi eşliğinde tarihî atmosferde kamp deneyimi sunar. Kaş ile Kalkan arasındaki Kaputaş Plajı yamaçları ve Kekova batık şehir manzaralı Üçağız koyu, deniz kenarı kampının en dramatik manzaralarını barındırır.",
      "Köprülü Kanyon Milli Parkı'nda Köprüçay Nehri'nin 400 metre derinliğindeki vadisi boyunca rafting sonrası nehir kenarı kampı, yaz aylarında su sıcaklığının serin kalması sayesinde sıcağa karşı doğal bir koruma sağlar. Geyikbayırı kaya tırmanışı bölgesindeki kamp alanları, tırmanışçı topluluğunun uluslararası buluşma noktasıdır. Kaş'tan Meis Adası'na (Kastellorizo) bakan kıyı şeridinde gece ışık kirliliği minimum düzeydedir ve yıldız gözlemi kamp programına eklenebilir. Likya Yolu boyunca su kaynakları yaz sonunda kuruyabilir; günlük 3 litrelik su taşıma planı çok günlük rotalarda zorunludur.",
      "Antalya Havalimanı ve D-400 karayolu Likya rotasının ana hub'ıdır: Kaş-Kalkan etapları batıda, Olympos-Çıralı orta kesimde, Adrasan-Gelidonya doğuda konumlanır. Mevsim matrisi patika-kanyon-kıyı üçgeninde okunur: nisan-mayıs Likya Way ideal sıcaklığı ve kaplumbağa sezonu öncesi, haziran-ağustos Köprülü rafting ve koy kalabalığı, eylül-ekim Caretta caretta yumurtlama dönemi (Olympos-Çıralı'da ışık kısıtlaması). Kaş-Kaputaş-Kekova-Olympos-Çıralı halkası, Likya etapları, kanyon raftingi ve kaplumbağa koruma kurallarını tek çok günlük programda birleştiren Antalya'nın en kapsamlı kamp koridorudur.",
      "Likya patikasında çok günlük kamp planlayanlar günlük en az üç litre su taşımalı; yaz sonunda kaynaklar kuruyabilir. Kaş-Kalkan kesimi deniz manzaralı ama gölgesiz, Köprülü Kanyon serin ama nehir taşkını riski taşır, Olympos-Çıralı ise gece ışık kısıtlamasına tabidir. Beş günlük rota Adrasan'dan başlayıp Gelidonya Feneri'nde gece kampı, Kaş-Kaputaş etabı ve Olympos'ta final ile tamamlanır.",
    ],
  },
  mersin: {
    paragraphs: [
      "Kızkalesi'nin deniz ortasındaki kale silueti manzaralı sahil şeridi, Akdeniz kıyısında antik kalıntı eşliğinde kamp yapmanın en ikonik adreslerinden biridir. Anamur'da muz bahçeleri arasındaki sıcak iklim, ocak ayında bile gece sıcaklığının sıfırın üzerinde kalmasını sağlayarak kış kampına imkân tanır. Silifke-Göksu Deltası'nda Nilüfer Platosu ve Alahan Manastırı çevresindeki kalkerli yamaçlar, kıyı sıcağından kaçmak isteyenler için 600 metre rakımda serin alternatifler sunar.",
      "Taşucu limanından Kıbrıs feribotlarına yakın kıyı alanları, gece liman ışıkları manzaralı kamp imkânı verir. Tarsus şehir merkezine yakın Berdan Nehri kıyısındaki yeşil alanlar, şehir kampı arayanlar için pratik seçenek oluşturur. Toros geçitlerinde Gülnar ve Mut yönünde yazın bile gece serinliği 12 dereceye düşer; kıyı-kontal arasındaki sıcaklık farkı aynı il içinde iki farklı ekipman setini gerektirir. Yazın Akdeniz'in en uzun gün ışığı süresi (14 saat) kamp aktivite planlamasını genişletir.",
      "Mersin-Adana otobanı kıyı şeridine, Anamur yolu muz bahçelerine, Silifke çıkışı Göksu Deltası ve Alahan Manastırı rotasına dağıtım sağlar. Mevsim matrisi kıyı-Toros ayrımıyla belirgindir: ocak-şubat Anamur'da ılıman kış kampı, mart-nisan Göksu Deltası kuş göçü, haziran-ağustos kıyı sıcağı ve 14 saat gün ışığı, eylül-ekim Toros serinliği. Kızkalesi-Taşucu limanı-Silifke Göksu Deltası halkası, antik kale manzarası, feribot hub'ı ve delta kuş gözlemini tek hafta sonu programında birleştiren Mersin'in imza rotasıdır.",
      "Kızkalesi kıyısı, Anamur iç kesimi ve Silifke Toros etekleri aynı il içinde farklı iklimler sunar: kıyı yazın sıcak ve nemli, Anamur ocak ayında bile gece sıfırın üzerinde, Toros geçitlerinde gece on iki dereceye düşer. Aynı hafta sonu kıyı kampı ile Toros serinliğini birleştirmek iki farklı ekipman seti gerektirir; kıyı aktivitelerini sabah erken ve akşamüstü saatlere yoğunlaştırmak gündüz sıcağından korur.",
    ],
  },
  hatay: {
    paragraphs: [
      "Samandağ'ın 14 kilometrelik kumsal şeridi, Akdeniz'in en uzun sahillerinden birinde deniz kaplumbağalarının yumurtlama alanlarına komşu kamp noktaları barındırır; yaz aylarında koruma alanları sınırlarına saygı gösterilmelidir. Harbiye şelalelerinin 40 metre yükseklikten akan suları çevresindeki çam ormanları, yaz ortasında 30 derecelik ova sıcağından 10 derece daha serin mikroklima oluşturur. Amanos Dağları'nın Belen geçidi üzerindeki orman yolları, İskenderun Körfezi manzaralı yüksek rakım kampı için ideal duraklardır.",
      "Antakya'nın Asi Nehri kıyısındaki yeşil şerit, şehir merkezine yakın kamp arayanlar için ulaşılabilir alternatif sunar. Arsuz ve Çevlik koylarında yazın nem oranı yüksektir; çadır içi yoğuşmayı önlemek için havalandırma kritiktir. Kasım-mart arası göçmen kuş döneminde Amik Ovası'nın sulak alanları kuş gözlemi kampını zenginleştirir. Hatay'ın zengin mutfak kültürü kamp rotasına Antakya künefesi ve biberli ekmek gibi yerel lezzet durakları ekler.",
      "Hatay, D-817 karayolu ve Belen geçidi üzerinden Amanos Dağları orman kampına, Samandağ kıyı şeridine ve Harbiye şelalelerine dağıtım sağlar; Gaziantep ve Adana bağlantıları bölgesel hub işlevi görür. Mevsim matrisi kıyı-dağ-koruma üçgeninde okunur: nisan-mayıs kaplumbağa sezonu öncesi sakin kıyılar, haziran-ağustos Samandağ koruma alanı kuralları ve nemli geceler, kasım-mart Amik Ovası kuş göçü. Harbiye şelaleleri-Belen geçidi-Amanos orman kampı halkası, aynı gün içinde serin mikroklima ile yüksek rakım manzarasını birleştiren Hatay'ın en verimli yerel rotasıdır.",
      "Samandağ kıyısında yaz aylarında Caretta caretta yumurtlama alanlarına saygı gösterilmeli; koruma bölgesi sınırları içinde ışık kullanımı kısıtlıdır. Harbiye şelaleleri ova sıcağından on derece serin, Amanos geçidi ise İskenderun manzaralı yüksek rakım kampı sunar. Çadır içi yoğuşmayı önlemek için nemli kıyı gecelerinde havalandırma kritiktir; kamp ateşi yerine gaz ocak tercih edilmelidir.",
    ],
  },
  artvin: {
    paragraphs: [
      "Kaçkar Dağları'nın 3937 metrelik zirvesine tırmanan 5 günlük trekking rotası, Yusufeli ilçesinden başlayarak Çoruh Vadisi boyunca yayla kamplarından geçer; bu rota Türkiye'nin en zorlu dağ kampı deneyimlerinden birini sunar. Macahel Vadisi'ndeki dünyanın birkaç örneğinde bulunan gürgen ormanları, Gürcistan sınırına yakın konumuyla benzersiz bir biyomda kamp imkânı verir. Çoruh Nehri'nin Yusufeli baraj gölü üzerindeki turkuaz suları, nehir kenarı kampının en etkileyici manzaralarından birini oluşturur.",
      "Yayla kültürü temmuz-ağustos döneminde zirve yapar; Kafkasör, Gorgit ve Hıdırnebi yaylalarında ahşap yayla evlerinin yanında çadır kurulabilir ve yerel peynir-ekmek tedariki mümkündür. Borçka Karagöl'ün siyah abies ormanları içindeki göl kenarı alan, gece sis bulutlarının su yüzeyine indiği fotojenik kamp noktaları sunar. Yusufeli-İspir arasındaki dar vadilerde gece sıcaklığı sıfırın altına düşebilir; yaz ortasında bile -5 dereceye kadar inen zirve geceleri için dört mevsim uyku tulumu şarttır. Çoruh'un coşkulu suları yağmur sonrası dere kenarı kamp alanlarını tehdit eder; su seviyesi sürekli izlenmelidir.",
      "Artvin ulaşımı Hopa-Rize karayolu ve Erzurum bağlantısı üzerinden Macahel biyosfer rezervi, Borçka Karagöl girişi ve Yusufeli Kaçkar zirve patikalarına dağılır. Mevsim matrisi rakıma göre keskin ayrılır: haziran-temmuz yayla açılışı ve çiçeklenme, temmuz-ağustos Kaçkar zirve trekking sezonu (3937 m), eylül-ekim altın orman ve erken kar riski, kasım-mayıs vadilerde yağış ve erişim kısıtı. Macahel gürgen ormanı-Borçka Karagöl-Yusufeli Kaçkar çıkış halkası, biyosfer, göl kenarı ve zirve trekking mevsimlerini tek çok günlük programda birleştiren Artvin'in en kapsamlı kamp koridorudur.",
      "Beş günlük Kaçkar rotası Yusufeli'nden başlayarak Çoruh Vadisi boyunca yayla kamplarından geçer; Macahel gürgen ormanında bir gece, Borçka Karagöl'de bir gece ve zirve öncesi son kamp noktasında dinlenme planlanır. Yağmur sonrası dere kenarı su seviyesi hızla yükselir; zirve gecelerinde dört mevsim uyku tulumu şarttır. Yayla döneminde yerel peynir-ekmek tedariki mümkündür.",
    ],
  },
  bolu: {
    paragraphs: [
      "Yedigöller Milli Parkı'nın yedi gölünü birbirine bağlayan 12 kilometrelik orman yolu, sonbahar aylarında sarı-kırmızı yaprak dökümü altında kamp yapmanın Türkiye'deki en klasik adreslerinden biridir. Abant Gölü'nün 1325 metre rakımdaki çam ormanları içindeki göl kenarı alanlar, yaz sıcağında bile serin geceler sağlar. Mudurnu'nun Osmanlı taş evleri arasındaki dar sokakların açıldığı vadi tabanları, tarihî kent dokusuna komşu sakin kamp noktaları barındırır.",
      "Kartalkaya kayak merkezinin yaz aylarında açık olan telesiyej hattı, 2200 metre rakımda geniş manzaralı kamp alanlarına erişim sağlar. D-100 karayolu üzerindeki Abant kavşağından Ankara'ya 2,5 saat, İstanbul'a 3 saat mesafe, Bolu'yu iki büyük şehrin hafta sonu orman kampı rotasının merkezi yapar. Gölcük Tabiat Parkı'nın volkanik göl çevresindeki çam ormanlarında hafta sonu yoğunluğu cumartesi sabah 08:00'den önce varış gerektirir. Yedigöller'de göl kenarı kamp alanları sınırlı olduğundan park girişinde erken saatlerde yer ayırtmak yaz sezonunda zorunludur; sonbahar ortasında gece sıcaklığı sıfırın altına düşer.",
      "İstanbul'dan D-100 ve otoyol ile Abant kavşağına 2,5 saat, Ankara'ya aynı mesafe; Abant-Yedigöller-Mudurnu rotası hafta sonu orman kampının klasik halkasıdır. Mevsim matrisi belirgindir: aralık-mart Kartalkaya kış kampı ve kar yağışı, nisan-mayıs Abant gölü çiçeklenmesi, haziran-ağustos serin orman geceleri, eylül-ekim Yedigöller yaprak dökümü altın sezonu. Abant sabah yürüyüşü-Yedigöller göl turu-Mudurnu Osmanlı sokakları akşam molası, İstanbul ve Ankara'dan tek gecelik çıkışla tamamlanabilecek Bolu'nun imza kamp rotasıdır.",
      "Yedigöller'de göl kenarı kamp alanları sınırlı olduğundan yaz sezonunda park girişinde cumartesi sabah sekizden önce varış yer ayırtmayı kolaylaştırır. Abant hafta sonları kalabalık, Mudurnu tenha ama düşük rakımlı, Kartalkaya yazın telesiyejle erişilebilir yüksek rakım sunar. Sonbahar ortasında Yedigöller'de gece sıcaklığı sıfırın altına düşer; termal içlik ve kış uyku tulumu şarttır.",
    ],
  },
  trabzon: {
    paragraphs: [
      "Uzungöl'ün 1090 metre rakımdaki göl kenarı çam ormanları, sis bulutlarının sabah göl yüzeyine indiği fotojenik kamp noktaları sunar; göl çevresindeki yürüyüş patikası 7 kilometre tam tur imkânı verir. Ayder Yaylası'nın kaplıca suları ve fırtına deresi boyunca uzanan asma köprüler, yayla kampını termal dinlenmeyle birleştiren benzersiz bir rota oluşturur. Sürmene bıçağı atölyelerinin bulunduğu kıyı ilçesinden Of'a uzanan sahil şeridi, deniz manzaralı düşük rakım kampı alternatifleri barındırır.",
      "Zigana Dağı'nın 2032 metre rakımlı geçidinde yaz aylarında bile sis ve yağmur ihtimali yüksektir; su geçirmez ekipman Karadeniz kampının vazgeçilmezidir. Hıdırnebi Yaylası'na çıkan 24 virajlı yol, temmuz-ağustos döneminde yayla şenlikleriyle canlanır. Pokut ve Sal yaylalarına Trabzon-Rize sınırından ulaşmak mümkündür; bu yaylalar bulut denizinin üzerinde kamp imkânı sunar. Fındık hasat dönemi (ağustos-eylül) kırsal yollarda traktör trafiğini artırır; kampçı araçları yol kenarına çekilirken tarım araçlarına yol verilmelidir.",
      "Trabzon Havalimanı Karadeniz kampının doğu hub'ıdır; Uzungöl'e 90 dakika, Ayder'e Rize sınırı üzerinden 2 saat, Sürmene kıyısına 45 dakika mesafe sunar. Mevsim matrisi yağış odaklıdır: nisan-mayıs çiçekli vadiler, haziran-ağustos yayla sezonu ve sis bulutları, eylül-ekim fındık hasadı ve altın orman, kasım-mart yoğun yağış ve erişim zorluğu. Uzungöl göl turu-Ayder kaplıca molası-Pokut yayla kampı halkası, göl, termal ve bulut üstü deneyimini birleştiren Trabzon-Rize sınırının imza rotasıdır.",
      "Uzungöl düşük rakımlı ve turistik, Ayder termal ama kalabalık, Pokut-Sal yaylaları ise bulut üstü en otantik kamp deneyimini sunar. Zigana geçidinde yaz bile sis ve yağmur ihtimali yüksektir; minimum üç bin milimetre su geçirmezlik dereceli çadır Karadeniz kampının vazgeçilmezidir. Fındık hasat döneminde kırsal yollarda traktör trafiğine karşı dikkatli olunmalıdır.",
    ],
  },
  rize: {
    paragraphs: [
      "Fırtına Vadisi'nde Tunca Köprüsü'nden Zil Kalesi'ne uzanan 30 kilometrelik dere kenarı rota, taş köprüler ve yosunlu kayalar arasında Karadeniz'in en dramatik kanyon kampını sunar. Pokut Yaylası'nın 2000 metre rakımdaki çayırlık düzlükleri, bulutların altında kamp kurulabilecek nadir yayla alanlarından biridir. Ayder'den Palovit Şelalesi'ne giden patika boyunca 15 metre yükseklikteki şelale sesi, orman içi kampın fon müziğini oluşturur.",
      "Çamlıhemşin ilçesindeki elevit yaylasına ulaşan stabilize yol, karavan erişimini sınırlar; çadır ve sırt çantası taşıma zorunludur. Yıllık 2500 milimetreyi aşan yağış miktarı, çadır seçiminde su geçirmezlik derecesini (minimum 3000mm) belirleyici kılar. Eylül ayında çay hasadı döneminde terraslı çay bahçeleri arasında yeşil tonların en yoğun olduğu manzaralar kamp fotoğrafçılığını zenginleştirir. Kaçkar trekking rotasının batı girişi Rize sınırlarında başlar; doğu çıkışı Artvin'e bağlanarak bölgesel çok günlük rotalar planlanabilir.",
      "Rize-Trabzon sahil yolu Fırtına Vadisi girişine, Çamlıhemşin yolu Elevit ve Ayder yaylalarına, İkizdere bağlantısı Kaçkar batı patikalarına dağıtım sağlar. Mevsim matrisi yağış ve yayla odaklıdır: mayıs-haziran vadi yeşillenmesi, temmuz-ağustos Pokut-Sal bulut üstü kampı, eylül çay hasadı altın tonları, ekim-kasım erken kar ve patika kapanışları. Tunca Köprüsü-Zil Kalesi-Palovit Şelalesi-Pokut yayla halkası, dere kenarı kanyon, şelale ve bulut üstü kampını tek çok günlük programda birleştiren Rize'nin imza rotasıdır.",
      "Fırtına Vadisi dere kenarı, Elevit yaylası ve Pokut platoları birbirinden belirgin ayrılır: vadi nemli ve sesli, Elevit stabilize yol nedeniyle karavansız, Pokut ise bulut üstü en dramatik manzarayı sunar. Yıllık 2500 milimetreyi aşan yağış çadır seçiminde minimum 3000mm su geçirmezlik gerektirir. Dört günlük rota Tunca Köprüsü'nden başlayıp Zil Kalesi molası, Palovit Şelalesi gece kampı ve Pokut'ta final ile tamamlanır.",
    ],
  },
  ankara: {
    paragraphs: [
      "Kızılcahamam'ın Soğuksu Milli Parkı'ndaki çam ormanları, başkente 80 kilometre mesafede belirlenmiş çadır alanları ve karavan parklarıyla hafta sonu orman kampının en erişilebilir adreslerinden biridir. Beypazarı'nın Osmanlı konakları arasındaki dar sokakların açıldığı Inözü Vadisi, kanyon manzaralı düşük rakım kampı alternatifleri sunar. Nallıhan Kuş Cenneti'nin tuz gölü manzaralı gözlem kuleleri, ilkbahar göç döneminde flamingo sürüleri eşliğinde kuş gözlemi kampını mümkün kılar.",
      "Gölbaşı Mogan Gölü kıyısındaki sazlık alanlar, şehir merkezine en yakın göl kenarı kamp noktalarını barındırır. İç Anadolu'nun karasal iklimi gece sıcaklığında 15 dereceye varan düşüşler yarattığından yaz aylarında bile termal içlik taşınmalıdır. Eymir ve Mogan göllerine ulaşım ODTÜ kampüsü güzergâhından sağlandığından araçsız kampçılar için otobüs alternatifi mevcuttur. Soğuksu Milli Parkı'nda yangın riski yüksek dönemlerde açık ateş tamamen yasaklanır; taşınabilir gaz ocak kullanımı zorunludur.",
      "Ankara-Eskişehir otoyolu Kızılcahamam Soğuksu Milli Parkı girişine, D-140 Beypazarı-Inözü Vadisi rotasına, Nallıhan Kuş Cenneti bağlantı yoluna dağıtım sağlar. Mevsim matrisi karasal iklimi yansıtır: mart-nisan kuş göçü ve Nallıhan flamingoları, mayıs-haziran Soğuksu çam ormanı ideal dönemi, temmuz-ağustos ova sıcağı ve gece serinliği, eylül-ekim Inözü kanyon sonbaharı. Soğuksu orman kampı-Beypazarı tarihî merkez molası-Nallıhan flamingo gözlemi halkası, başkente en yakın doğa-tarih-kuş gözlemi rotasını oluşturur.",
      "Soğuksu Milli Parkı, Beypazarı Inözü Vadisi ve Nallıhan Kuş Cenneti üç farklı kamp tipi sunar: orman belirlenmiş alanlarda organize, Inözü kanyon manzaralı ama düşük rakımlı, Nallıhan ise kuş gözlemi odaklıdır. İç Anadolu'da gece sıcaklığı on beş derece düşebilir; yaz aylarında bile termal içlik taşınmalıdır. Yangın riski yüksek dönemlerde açık ateş yasaktır; taşınabilir gaz ocak zorunludur.",
    ],
  },
  konya: {
    paragraphs: [
      "Beyşehir Gölü'nün 650 kilometrekarelik yüzey alanı, Türkiye'nin en büyük tatlı su gölü kıyısında kamp yapma imkânı sunar; Anamas Dağı'nın gölde yansıyan silueti gün batımı kampının en geniş manzarasını oluşturur. Taşkent ilçesindeki Zindan Mağarası çevresindeki Toros etekleri, yaz sıcağından kaçmak isteyenler için 1200 metre rakımda serin kamp alanları barındırır. Hadim (Akseki) yönündeki Gembos Ovası, geniş düzlükleriyle açık gökyüzü kampı ve yıldız gözlemi için ideal koşullar sağlar.",
      "Çatalhöyük arkeolojik alanına yakın Çumra ovasında gece kampı tarım arazileri nedeniyle sınırlıdır; Beyşehir kıyısındaki milli park alanları resmi kamp için uygun seçeneklerdir. Tuz Gölü'nün kuzey kıyısındaki kayacık tuz oluşumları, benzersiz bir peyzajda fotoğraf kampı imkânı verir. Konya ovasında yaz gündüz sıcaklığı 38 dereceye çıkarken Toros yaylalarında 22 derece ölçülür; aynı hafta sonu içinde ova-yayla kampı birleştirmek ekipman açısından zorlayıcıdır. Mevlana şehri olarak bilinen merkezden doğa alanlarına ulaşım D300 karayolu üzerinden sağlanır.",
      "D300 karayolu Beyşehir Gölü kıyı kampına, Hadim yolu Taşkent Zindan Mağarası rotasına, Tuz Gölü kuzey kıyısındaki kayacık oluşumlarına dağıtım sağlar. Mevsim matrisi ova-Toros ayrımıyla keskindir: nisan-mayıs Beyşehir göl kenarı çiçeklenmesi, haziran-ağustos ova sıcağı (38°C) ve yayla kaçışı, eylül-ekim Tuz Gölü fotoğraf altın saati. Beyşehir göl kampı-Taşkent Toros serinliği-Gembos Ovası yıldız gözlemi halkası, aynı il sınırları içinde göl, dağ ve açık gökyüzü kampını birleştiren Konya'nın imza rotasıdır.",
      "Beyşehir Gölü, Taşkent Toros etekleri ve Tuz Gölü kuzey kıyısı aynı hafta sonunda karşılaştırıldığında belirgin farklar ortaya çıkar: göl kenarı geniş manzaralı, Toros on altı derece daha serin, Tuz Gölü benzersiz fotoğraf peyzajı sunar. Ova gündüz otuz sekiz dereceye çıkarken yaylada yirmi iki derece ölçülür; iki farklı ekipman seti taşımak zorlayıcı olabilir, bu yüzden tek bölgeye odaklanmak daha pratiktir.",
    ],
  },
  nevsehir: {
    paragraphs: [
      "Ihlara Vadisi'nin 14 kilometrelik kanyon tabanında Melendiz Suyu'nun akışı eşliğinde kamp yapmak, yükseltilmiş kaya yüzeylerindeki freskli kiliselerin gölgesinde benzersiz bir deneyim sunar. Göreme Açık Hava Müzesi çevresindeki peri bacaları arasında belirlenmiş kamp alanları, dünyada eşi az bulunur bir jeolojik peyzajda çadır kurulmasına olanak tanır. Soğanlı Vadisi'ndeki kaya oyma kiliseler ve güvercinlikler, kalabalık Göreme rotasına alternatif sakin kamp noktaları barındırır.",
      "Erciyes Dağı'nın 3917 metrelik zirvesine tırmanış rotası, Temmuz-Ağustos döneminde kar sınırının üzerinde kamp gerektirir; bu rota deneyimli dağ kampçılarını hedefler. Kapadokya'da gece sıcaklığı yazın bile 8 dereceye düşer; gündüz-gece arasındaki 20 derecelik fark termal ekipman zorunluluğu yaratır. Balon turlarının gün doğumunda kalkış saatleri (05:30-06:30) kamp alanlarında kısa süreli gürültü ve gökyüzü trafiği yaratır. Peri bacalarının kumtaşı yapısı çadır kazıklarının sağlam yerleştirilmesini zorlaştırır; kaya bloklarına sabitleme tercih edilmelidir.",
      "Nevşehir-Göreme merkezi Ihlara Vadisi girişine, Uçhisar yolu Soğanlı Vadisi rotasına, Erciyes kayak merkezi bağlantı yoluna dağıtım sağlar. Mevsim matrisi balon ve sıcaklık odaklıdır: nisan-mayıs çiçekli vadiler ve ılıman geceler, haziran-ağustos balon sezonu zirvesi ve gece 8°C, eylül-ekim tenha peri bacaları ve fotoğraf altın saati. Ihlara kanyon yürüyüşü-Göreme peri bacası kampı-Soğanlı Vadisi sakin alternatif halkası, kanyon, jeolojik peyzaj ve tarihî kilise rotalarını birleştiren Kapadokya'nın imza kamp programıdır.",
      "Ihlara Vadisi, Göreme peri bacaları ve Soğanlı Vadisi üç farklı Kapadokya deneyimi sunar: kanyon tabanı serin ve gölgeli, Göreme turistik ama jeolojik açıdan eşsiz, Soğanlı ise en sakin alternatiftir. Balon turları gün doğumunda 05:30-06:30 arası kalkış yapar; bu saatlerde kısa süreli gürültü beklenmelidir. Peri bacası kumtaşı zemin çadır kazıklarını zorlaştırır; kaya bloklarına sabitleme tercih edilmelidir.",
    ],
  },
  erzurum: {
    paragraphs: [
      "Tortum Gölü'nün 8 kilometre uzunluğundaki kıyı şeridi ve 48 metrelik Tortum Şelalesi, Doğu Anadolu'nun en etkileyici göl kenarı kamp manzaralarını sunar. Palandöken Dağı'nın 3176 metre rakımlı zirvesinde yaz aylarında kar kalıntıları arasında kamp kurulabilir; kış aylarında -30 dereceye inen sıcaklıklar kar kampı için zorlu koşullar yaratır. Narman Peribacaları'nın kırmızı kumtaşı oluşumları, Kapadokya'ya benzer ama daha az bilinen bir peyzajda fotoğraf kampı imkânı verir.",
      "Oltu ilçesindeki Oltu taşı atölyelerinin bulunduğu vadi tabanı, tarihî taş köprüler eşliğinde düşük rakım kampı alternatifleri sunar. Erzurum ovasında yaz gündüz sıcaklığı 28 dereceye çıksa da gece sıcaklığı 5 derecenin altına düşer; yüksek rakımlı Tortum'da gece donma riski vardır. Konaklı kayak merkezinin yaz aylarında açık olan tesisleri, dağ kampına duş ve tuvalet erişimi sağlar. Çifte Minareli Medrese çevresindeki şehir merkezinden Palandöken'e ulaşım 20 dakikalık mesafededir.",
      "Erzurum Havalimanı Doğu Anadolu kampının batı hub'ıdır; Tortum Gölü'ne 90 dakika, Palandöken kayak merkezine 20 dakika, Oltu vadisine 45 dakika mesafe sunar. Mevsim matrisi ekstrem sıcaklıklarla belirgindir: haziran-ağustos Palandöken yaz trekking ve kar kalıntıları, eylül-ekim Tortum sonbahar manzarası, kasım-mart -30°C kar kampı. Tortum Gölü kıyı kampı-Tortum Şelalesi molası-Palandöken zirve manzarası halkası, göl, şelale ve yüksek rakım deneyimini birleştiren Erzurum'un imza rotasıdır.",
      "Tortum Gölü kıyısı, Palandöken zirvesi ve Oltu vadisi üç farklı rakım ve iklim sunar: göl kenarı serin ve rüzgârlı, Palandöken yazın bile kar kalıntılı, Oltu düşük rakımlı ve tarihî. Ova gündüz yirmi sekiz dereceye çıksa da gece beş derecenin altına düşer; Tortum'da donma riski vardır. Üç günlük rota cumartesi Tortum'da gece kampı, pazar şelale molası ve pazartesi Palandöken zirve manzarasında final ile planlanabilir.",
    ],
  },
  van: {
    paragraphs: [
      "Van Gölü'nün 3713 kilometrekarelik mavi suları kıyısında kamp kurmak, alkali gölün turkuaz tonlarında yüzmek anlamına gelir; göl suyu tuzlu ve acı olduğundan içme suyu ayrı taşınmalıdır. Akdamar Adası'ndaki On İkinci Yüzyıl kilisesi manzaralı kıyı noktaları, adaya tekne ile ulaşım gerektiren özel kamp rotaları oluşturur. Süphan Dağı'nın 4058 metrelik volkanik zirvesine tırmanış rotası, yaz aylarında buzul sınırında kamp gerektirir.",
      "Muradiye Şelalesi'nin 50 metre yükseklikten döküldüğü noktada kanyon kampı, yaz ortasında serin hava akımı sağlar. Van-Hakkari karayolu üzerindeki Çaldıran Ovası, geniş düzlükleriyle açık gökyüzü kampı ve yıldız gözlemi için ideal koşullar sunar. Göl kıyısında rüzgâr genellikle öğleden sonra kuvvetlenir; çadır kurulumu sabah saatlerinde tamamlanmalıdır. Van kedisi ve otlu peynir geleneği, kamp rotasına Edremit kavurması ve kahvaltılık peynir tedarik imkânı ekler.",
      "Van Ferit Melen Havalimanı göl kıyısı kampının hub'ıdır; Edremit kavurması durakları, Akdamar Adası tekne iskelesi ve Muradiye Şelalesi rotası buradan dağılır. Mevsim matrisi yüksek rakım odaklıdır: haziran-ağustos göl yüzme sezonu ve Süphan trekking, eylül-ekim tenha kıyılar ve hasat, kasım-nisan kar ve göl donması riski. Van Gölü kıyı kampı-Akdamar Adası tekne turu-Muradiye Şelalesi kanyon halkası, alkali göl, adalar arası ulaşım ve şelale mikroklimasını birleştiren Van'ın imza rotasıdır.",
      "Van Gölü kıyısında çadır kurulumu öğleden önce tamamlanmalı; rüzgâr öğleden sonra kuvvetlenir. Göl suyu alkali ve acı olduğundan içme suyu ayrı taşınmalıdır. Edremit kavurması ve otlu peynir tedarik noktaları rotaya pratik mola ekler. Dört günlük program cumartesi göl kıyısında kamp, pazar Akdamar tekne turu, pazartesi Muradiye Şelalesi kanyon molası ve salı Çaldıran Ovası'nda yıldız gözlemi ile tamamlanır.",
    ],
  },
  sanliurfa: {
    paragraphs: [
      "Halfeti'nin Birecik barajı suları altında kalan eski yerleşim manzarası, Fırat kıyısında su altı kalıntıları eşliğinde kamp yapmanın Türkiye'deki en özgün adreslerinden biridir. Göbeklitepe arkeolojik alanına 15 kilometre mesafedeki Harran ören yerinin kubbeli evleri, tarih öncesi tapınaktan Roma dönemine uzanan kamp rotasına kültür derinliği katar. Birecik kıyısında bald ibis koruma alanı yakınında kamp yapılırken nesli tehlikedeki türlere saygı gösterilmelidir.",
      "Soğmatar antik güneş tapınağı çevresindeki açık platolar, Mezopotamia ovasının uçsuz bucaksız manzarasında gece yıldız gözlemi kampı için idealdir. Fırat kıyısında yaz gündüz sıcaklığı 42 dereceye çıkar; kamp aktiviteleri gün doğumu ve gün batımı saatlerine yoğunlaştırılmalıdır. Harran'dan Suriye sınırına uzanan düzlüklerde rüzgâr sürekli eser; kum fırtınası riskine karşı gözlük ve yüz koruyucu taşınmalıdır. Urfa merkezindeki Balıklıgöl çevresinden Halfeti'ye D875 karayolu üzerinden 1,5 saatte ulaşılır.",
      "D875 karayolu Halfeti su altı kalıntılarına, Harran-Göbeklitepe arkeolojik rotasına, Birecik bald ibis koruma alanına dağıtım sağlar. Mevsim matrisi sıcaklık odaklıdır: mart-nisan ılıman geceler ve Göbeklitepe ziyareti, mayıs-haziran Fırat kıyısı serin sabahlar, temmuz-ağustos 42°C gündüz sıcağı (gece kampı zorunlu), eylül-ekim Harran pus tabakası altın saati. Halfeti tekne turu-Göbeklitepe sabah ziyareti-Soğmatar yıldız gözlemi halkası, su altı tarih, arkeoloji ve Mezopotamia gece gökyüzünü birleştiren Şanlıurfa'nın imza rotasıdır.",
      "Halfeti, Harran ve Soğmatar aynı il sınırlarında farklı kamp karakterleri sunar: Halfeti Fırat kıyısında su altı kalıntı manzaralı, Harran kubbeli evler arasında tarihî, Soğmatar ise açık plato üzerinde yıldız gözlemi odaklıdır. Yaz gündüz sıcağı kırk iki dereceye çıktığından aktiviteler gün doğumu ve gün batımına yoğunlaştırılmalıdır. Harran düzlüklerinde kum fırtınası riskine karşı gözlük ve yüz koruyucu taşınmalıdır.",
    ],
  },
  mardin: {
    paragraphs: [
      "Mardin kalesinin surlarından Mezopotamia Ovası'na bakan teraslı taş evlerin arasında kamp kurmak, gün doğumunda Suriye sınırına kadar uzanan sis tabakasını izleme imkânı sunar. Midyat'ın süryani kiliseleri ve gümüş işçiliği atölyelerinin bulunduğu taş mahalleler, kültür rotasına entegre edilebilecek kamp durakları oluşturur. Dara antik kentinin Roma dönemi su sarnıçları ve amfitiyatrosu çevresindeki açık alanlar, tarihî atmosferde gece kampı için benzersiz bir peyzaj sunar.",
      "Mazı Dağları'nın 1200 metre rakımlı eteklerinde steppe bitki örtüsü arasında yaz aylarında serin gece kampı mümkündür; ova sıcaklığından 12 derece daha düşük sıcaklık ölçülür. Nusaybin sınır kapısına yakın kırsal alanlarda güncel güvenlik bilgileri takip edilmelidir. Taş evlerin gölgesinde kamp kurulurken tarihî yapılara zarar verilmemesi ve yerel toplulukların mahremiyetine saygı gösterilmesi kritiktir. Ekim-kasım döneminde ova üzerindeki pus tabakası sabah saatlerinde en yoğun halini alır ve fotoğraf kampı için altın saati yaratır.",
      "D-950 karayolu Mardin taş teras merkezine, Midyat gümüş atölyeleri rotasına, Dara antik kent bağlantı yoluna dağıtım sağlar. Mevsim matrisi pus ve sıcaklık odaklıdır: mart-nisan bahar yeşillenmesi, haziran-ağustos ova sıcağı ve Mazı Dağları serinliği, ekim-kasım pus tabakası altın saati. Mardin kale seyir-Midyat taş mahalle molası-Dara antik kent gece kampı halkası, teraslı manzara, kültür rotası ve Roma dönemi peyzajını birleştiren Mardin'in imza programıdır.",
      "Üç günlük Mardin rotası cumartesi kale seyir terasında gün doğumu, pazar Midyat taş mahallelerinde kültür molası ve pazar gece Dara antik kent amfitiyatrosu çevresinde kamp ile tamamlanır. Mazı Dağları etekleri ova sıcağından on iki derece daha serindir; yaz aylarında gece kampı için ideal kaçış noktasıdır. Tarihî taş yapılara zarar verilmemesi ve yerel toplulukların mahremiyetine saygı gösterilmesi kritiktir.",
    ],
  },
  gaziantep: {
    paragraphs: [
      "Rumkale'nin Fırat ve Merzimen nehirlerinin birleştiği noktada yükselen surları, nehir kenarı kampının en etkileyici tarihî fonunu oluşturur; kaleye tekne ile ulaşım yaz aylarında düzenli seferlerle sağlanır. Nizip ilçesindeki Karkamış antik kenti yakınlarında Fırat kıyısındaki kum tepeleri, Mezopotamia ovasının geniş manzarasında açık gökyüzü kampı imkânı verir. Nurdağları'nın 1500 metre rakımlı orman kesimlerinde çam ağaçları arasında yaz ortasında serin kamp kurulabilir.",
      "Dülük antik kentinin mağara yerleşimlerinin bulunduğu platolar, arkeolojik alan yakınında dikkatli kamp kurulumu gerektirir. Gaziantep ovasında yaz gündüz sıcaklığı 40 dereceyi aşarken Nurdağları'nda 28 derece ölçülür; aynı gün içinde ova-dağ geçişi ekipman planlamasını zorlaştırır. Zeugma mozaik müzesinin bulunduğu şehir merkezinden Rumkale'ye Nizip üzerinden 45 dakikalık mesafe, tarih ve doğa kampını birleştiren rotalar planlamayı kolaylaştırır. Fırat kıyısında ilkbahar taşkın döneminde su seviyesi yükselir; nehir kenarı kamp alanı seçiminde dikkatli olunmalıdır.",
      "O-52 otoyolu Gaziantep merkezinden Nizip-Rumkale Fırat kıyısına, Nurdağları orman yollarına ve Karkamış antik kent rotasına dağıtım sağlar. Mevsim matrisi ova-dağ ayrımıyla okunur: mart-nisan Fırat taşkın dönemi (nehir kenarı dikkat), mayıs-haziran Rumkale tekne seferleri, temmuz-ağustos ova sıcağı ve Nurdağları kaçışı, eylül-ekim Karkamış sakin ziyaret. Rumkale tekne turu-Nurdağları serin orman kampı-Karkamış antik kent molası halkası, nehir, dağ ve arkeolojiyi birleştiren Gaziantep'in imza rotasıdır.",
      "Rumkale nehir kenarı, Nurdağları ormanı ve Karkamış ova kıyısı aynı gün içinde birleştirilebilir: ova gündüz kırk dereceyi aşarken Nurdağları'nda yirmi sekiz derece ölçülür. İlkbahar taşkın döneminde Fırat su seviyesi yükselir; nehir kenarı kamp alanı seçiminde dikkatli olunmalıdır. Cumartesi sabah Rumkale tekne turu, öğleden sonra Nurdağları serin orman kampı ve pazar Karkamış ziyareti en dengeli hafta sonu programını oluşturur.",
    ],
  },
};
